try {
    (() => {
        var e = __$$hmAppManager$$__.currentApp;
        var t = e.current,
            {
                px: o
            } = (new DeviceRuntimeCore.WidgetFactory(
            new DeviceRuntimeCore.HmDomApi(e, t)),
            e.app.__globals__);
        try {
            (() => {
                var e = __$$hmAppManager$$__.currentApp,
                    t = e.current;
                new DeviceRuntimeCore.WidgetFactory(
                new DeviceRuntimeCore.HmDomApi(e, t),
                    "drink");
                DeviceRuntimeCore.HmLogger.getLogger("sanjiao");
                t.module = DeviceRuntimeCore.Page({
                    init_view() {
                        hmUI.setLayerScrolling(false); //禁用页面上下滑动
                        function splitStringByCount(str, count) {
                              const arr = [];
                              for (let i = 0; i < str.length; i += count) {
                                arr.push(str.substr(i, count));
                              }
                              return arr;
                            }
                        function randomNum(lowerInteger, upperInteger) {
                        	 let choices = upperInteger - lowerInteger + 1;
                        	 return Math.floor(Math.random() * choices + lowerInteger);
                        }
                        var sn=0
                        var word={}
                        word.raw_word=`avant-garde|n.先锋派,前卫,(复)前哨部队
rapture|n.全神贯注,兴高采烈,欢天喜地vt.使狂喜
spatially|adv.空间地,存在于空间地
assignment|n.分配,委派,任务,(课外)作业
builder|n.建筑者,施工人员,营造商,增洁剂
inconsonant|adj.不协调的,不协和的,不一致的
ankle|n.[解]踝
lackluster|n.无光泽,暗淡
downstream|adv.下游地adj.下游的
stateroom|n.[船]特等客舱,[火车]高级包厢,政府公寓
megalith|n.[考古](古建筑用的)巨石
controlled|adj.受约束的,克制的
sultry|adj.闷热的,粗暴的,激烈的,放荡的
marquee|n.大帐篷,华盖n.[计]选取框
reconstruct|v.重建,改造,推想
aggravation|n.,加重(病情、负担、罪行、危机等的),更恶化,恼怒
toleration|n.忍受
conferee|n.参加会议者
protest|n.主张,断言,抗议v.主张,断言抗议,拒付
apothecary|n.药剂师,药师
dipper|n.浸渍者,汲取的人,浸染工,显影液容器,北斗七星
eternal|adj.永恒的,永远的,不灭的,没完没了的
diabolically|
pretentiousness|自负
discerning|adj.有辨识能力的
plead|vi.辩护,恳求vt.为...辩护,借口,托称
uproarious|adj.骚动的
paleontologist|n.古生物学者
viscosity|n.粘质,粘性
speleology|n.洞穴学
cyan|n.蓝绿色,青色
terribly|adv.可怕地,十分,极
executor|n.被指定遗嘱执行者,执行者
titanium|n.[化]钛
platform|n.(车站)月台,讲台,讲坛平台
self-explanatory|adj.自明的,不需加以说明的
rose|n.蔷薇属,玫瑰,玫瑰红vbl.rise的过去式
conceive|vt.构思,以为,持有vi.怀孕,考虑,设想
draftsman|n.起草人,立案者,绘图员
tongs|n.钳子,夹具
breeze|n.微风,煤屑,焦炭渣,轻而易举的事,小风波vi.吹微风,逃走
colonization|n.殖民地化,殖民
append|vt.附加,添加,悬挂[计]设置数据文件的搜索路径
beatitude|n.至福,祝福
disclose|vt.揭露,透露
tumbler|n.打滚的人,翻筋斗者,杂技演员,(平底)大玻璃杯,一杯量
chuckle|n.吃吃的笑声vi.吃吃的笑,咯咯叫
underplay|vt.使没有充分发挥作用,扣着大牌不出而出小牌,表演有克制,对...轻描淡写,表演不充分vi.表演角色不充分n.秘密行动,不充分的表演
ventilator|n.通风设备,空调机
touchdown|n.[美橄]攻方持球,触地,触地得分,着地,降落
reminiscent|adj.回忆往事的
armour|n.盔甲,装甲钢板,装甲部队
hearer|n.听者,听众
drowsy|adj.昏昏欲睡的,催眠的,(街、市等)沉寂的
rumpled|弄绉
clamorous|adj.大喊大叫的
development|n.发展
incongruent|adj.不一致的
inconsistency|n.矛盾
infelicitous|adj.不吉利的,不幸的,不合适的
beef|n.牛肉
bookcase|n.书架,书柜
point|n.点,尖端,分数,要点,分数vt.弄尖,指向,指出,瞄准,加标点于vi.指,指向,表明
satirically|
interpretation|n.解释,阐明,口译,通译
harassment|n.折磨
torn|vbl.tear的过去分词
goodish|adj.尚好的,相当好的,颇的
buyer|n.买主,顾客,采购员
accuracy|n.精确性,正确度
presumption|n.假定
bookmark|n.书签
inscribe|v.记下
populace|n.平民
golf|n.高尔夫球vi.打高尔夫球
stranded|adj.束手无策的；进退两难的
serfdom|n.农奴身份,农奴境遇
abolish|vt.废止,废除(法律、制度、习俗等)
forecourt|n.前院,<美>(篮球)前(场)球
phalanx|n.方阵,密集队,密集人群,[解]指骨,趾骨
yank|v.n.猛拉
chorus|n.合唱,合唱队,齐声
recriminatory|adj.互相责备的,反控诉的
concise|adj.简明的,简练的
conciliatory|adj.抚慰的,调和的
indifference|n.不关心
reminiscent|adj.回忆往事的
unadulterated|adj.没有搀杂的
oration|n.演说,致辞,叙述法[语]引语
artful|adj.巧妙的,狡猾的
bulldoze|v.威吓,欺负
glimmer|v.闪烁n.闪光
oracle|n.[宗](古希腊)神谕,预言,神谕处,神使,哲人,圣贤美国ORACLE公司,主要生产数据库产品,也是主要的网络计算机的倡导者
moccasin|n.鹿皮鞋,软拖鞋
conclusion|n.结束,缔结,结论
distastefully|
swath|n.收割的刈痕,细长的列
ship|n.船,海船,舰v.装上船,航运,载运,在船上工作
row|n.排,行v.划(船)
shapely|adj.样子好的,匀称的,形状美观的,定形的,有条理的
predicament|n.困境
inadmissibility|n.不许可的事,难承认的事
fuddle|vt.灌醉,使迷糊,使烂醉vi.狂饮n.烂醉
propitious|adj.吉利的
mealymouthed|adj.转弯抹角说的,不敢直说的
valid|adj.[律]有效的,有根据的,正当的,正确的
antelope|n.羚羊
ache|n.疼痛vi.觉得疼痛,渴望
empire|n.帝国,帝权
adhere|vi.粘附,胶着,坚持v.坚持
manikin|n.侏儒,人体模型,时装模特
finally|adv.最后,终于,不可更改地,决定性地
slur|v.忽视n.污点
immanent|adj.内在的,固有的,[宗](上帝)无所不在的
spun|vbl.spin的过去式和过去分词adj.纺成的
bequest|n.遗产,遗赠
tractable|adj.易驾驭的,驯良的,易管教的,易处理的
recommendable|值得推荐的,可取的
emend|vt.修订,校勘
matteo|matteo
statistically|adv.统计上地,统计地
equivocate|vi.说模棱两可的话,支吾
entail|vt.使必需,使蒙受,使承担,遗传给n.[建]限定继承权
hullabaloo|n.喧嚣,喧哗,吵闹（声）,（混乱,骚动）声
hosepipe|n.橡胶软管
silverware|n.银器
year|n.年,年龄,年岁
facile|adj.易做到的,易得到的,不花力气的,敏捷的,流畅的,(性格)柔顺的,温和的,容易的
fairyland|n.仙境,乐园,奇境
irritable|adj.易怒的,急躁的
lonesome|adj.寂寞的
swallow|n.[鸟]燕子,吞咽,喉vt.咽,淹没,吞没,取消,忍受,轻信,压制,耗尽vi.吞下,咽下
somewhat|adv.稍微,有点,有些
prism|n.[物]棱镜,[数]棱柱
lemon|n.柠檬adj.柠檬色的
mustard|n.芥菜,芥末,芥末色,芥子气
precise|adj.精确的,准确的n.精确
gland|n.[解剖]腺,[机械]密封管
residency|n.住处,住院医生实习期,住院医生的职位,高级训练(阶段)
imposter|冒名顶替者
reaction|n.反应,反作用,反动(力)
salesclerk|n.商店里的店员
recitalist|
bikini|n.(三角裤与胸罩分开的)比基尼泳装
furl|vt.卷收,叠,收下vi.卷起,收拢n.卷收,卷起之物,卷起
staunch|adj.坚定的
coincident|adj.一致的,符合的,巧合的
decibel|n.分贝
savings|储蓄
pulpit|n.(教堂的)讲道坛
bookcase|n.书架,书柜
worship|n.崇拜,礼拜,尊敬vi.敬神,拜神vt.崇拜,尊敬
infallible|adj.没有错误的,确实可靠的n.一贯正确的人
necrosis|n.坏疽,骨疽
affability|n.和蔼,亲切
technic|n.技术,手法
jocund|adj.欢乐的,高兴的
devoid|adj.全无的,缺乏的
mutable|adj.易变的,性情不定的
cohesive|adj.粘着的
laudably|adv.值得赞赏地,可称赞地
maximize|vt.取...最大值,最佳化
harpoon|n.(捕鲸用)鱼叉vt.用鱼叉叉,用鱼叉捕获
rapid|adj.迅速的,飞快的,险峻的n.急流,高速交通工具,高速交通网
consume|vt.消耗,消费,消灭,大吃大喝,吸引vi.消灭,毁灭
relieve|vt.减轻,解除,援救,救济,换班
veritable|adj.真正的
huff|vt.把...吹胀,激怒,发怒vi.吹气,恫吓,发怒n.发怒,提高价格
vestment|n.外衣,制服,衣服,法衣,祭坛布
domineer|v.压制
signal|n.信号adj.信号的v.发信号,用信号通知
diabetes|n.[医]糖尿病,多尿症
boyish|adj.少年的,孩子气的
transferability|n.可转让性,可转移性
elate|vt.使兴高采烈,使得意
repel|vt.击退,抵制,使厌恶,使不愉快
obstinate|adj.倔强的,顽固的
daub|v.涂抹
musicianship|n.音乐技巧,音乐感,音乐才能,音乐修养,音乐鉴赏力
enhance|vt.提高,增强v.提高
fellow|n.人,家伙,伙伴,学会特别会员,朋友,同事adj.同伴的,同事的,同道的
substantively|adv.实质上
eyelid|n.眼皮,眼睑
sprawling|无计划地占用山林农田建造厂房(的)
counteraction|n.反对的行动,抵抗,反动
lotion|n.洗液,洗剂
aridity|n.干旱,乏味
intolerance|n.(尤指对别人的意见)不能忍耐,不容异说,偏狭,[医](对食物,药物等)不耐性
merrily|adv.愉快地,高兴地
methodology|n.方法学,方法论
chord|n.弦,和音,情绪n.[解]腱
abuse|n.滥用,虐待,辱骂,陋习,弊端v.滥用,虐待,辱骂
bilingual|adj.能说两种语言的
bevy|n.一群鸟,一群(少女或少妇),<俗>一堆东西,一群人
crater|n.弹坑
further|adj.更远的,更多的,深一层的vt.促进,增进,助长adv.更进一步地,更远地,此外
exaggerate|v.夸大,夸张
fiber|n.fibre光纤
brutal|adj.残忍的,兽性的
vocal|adj.发嗓音的,声音的,有声的,歌唱的n.元音,声乐作品
unfavorable|adj.不宜的,不顺利的,相反的,令人不快的
acquisitiveness|渴望得到
spill|n.溢出,溅出,摔下,木片,小塞子,暴跌,溢出量vt.使溢出,使散落,洒,使流出,使摔下,倒出vi.溢出,涌流,充满
judiciousness|
palisade|n.木栅vt.用栅栏围护
male|adj.男的,雄的,男性
calvinist|
ill-natured|adj.心地不良的,歪曲的
wish|n.愿望,心愿,请求,所愿望的事物,祝愿v.希望,想要,但愿,祝贺
booster|n.<美俚>热心的拥护者,后推的人,支持者,后援者,调压器
incarceration|n.钳闭
rancid|adj.象油脂腐臭味的,腐臭的
pig|n.猪,猪肉,贪婪的人v.生小猪,贪婪地吃
screwdriver|n.螺丝起子
packet|n.小包裹,小捆v.包装信息包
ask|vi.询问,问,要求vt.问,要求,需要,邀请
speciality|n.特性,特质,专业,特殊性
depute|v.委托
satirize|v.讽刺性描写
soulful|adj.充满热情的,深情的,感情上的,高尚的
astray|adv.迷途地,入歧途地
lesser|adj.较小的,更少的,次要的
irreligious|adj.没有宗教信仰的,无宗教的,无信仰的
gang|n.(一)伙,(一)群
variant|adj.不同的n.变量
prompting|n.促进,激励,提示
toga|n.宽外袍,参议员的职位
hearth|n.壁炉地面,炉边,家庭（生活）,炉膛
unforgettable|adj.忘不了的,令人难忘的
opprobrious|adj.嘴不干净的,无礼的,粗野的,该骂的,可耻的
joke|n.笑话,玩笑v.(和...)开玩笑
amend|v.修正,改进,改正
haughtily|adv.傲慢地,骄傲地
acquisitive|adj.想获得的,有获得可能性的,可学到的
teeter|v.步履蹒跚,摇摇欲坠
flawed|有裂纹的,有瑕疵的有缺陷的
dentistry|n.牙科
mannerism|n.(言语、写作中的)特殊习惯,怪癖
scary|adj.引起惊慌的
squat|v.蹲坐,蹲伏n.蹲坐adj.蹲着的
infrequent|adj.稀少的,很少发生的,罕见的
stigma|n.污名,(植物)柱头,[动物]气门,耻辱
flat|adj.平坦的,扁平的,单调的,倒下的,浅的,干脆的,无聊的,无力的adv.平直地,仰卧地,恰恰,正好,断然地n.平面,平地,一层,公寓v.(使)变平,(使)降半音
latency|n.潜伏,潜在,潜伏物,性潜伏期（4岁或5岁至青春期）,[生理]（肌肉等的）反应时间（介于刺激与反应之间的时间）
overdue|adj.迟到的
whit|n.些微,一点点
platform|n.(车站)月台,讲台,讲坛平台
contrivance|n.发明,发明才能,想出的办法,发明物
indigestion|n.消化不良
shibboleth|n.口令
broach|vt.给...开口,钻孔,开始讨论,提出
font|n.字体,字形,洗礼盘,泉,圣水器
compaction|n.压紧,紧束之状态
bewitch|vt.施魔法于,蛊惑,迷人
frightful|adj.可怕的,非常的
wring|v.绞,扭,榨取,强求,折磨,扭绞n.绞,挤,榨,扭动
potentate|n.当权者
regality|n.君权,王位,王国,国王的特权
equipoise|n.平衡,均衡
depressed|adj.沮丧的,降低的
ecstatic|n.狂喜的人adj.狂喜的,心醉神迷的,入迷的
grippingly|
resoluteness|坚决
strontium|n.锶
conspicuousness|显著，卓越，突出
thematically|
cage|n.笼,槛,(矿井)贯笼
tamper|vi.干预,玩弄,贿赂,损害,削弱,篡改vt.篡改n.捣棒,夯,填塞者
run-down|n.刺杀出局,纲要,总结
thrifty|adj.节约的
fanfare|n.喇叭或号角嘹亮的吹奏声,吹牛
tugboat|n.拖船,拖轮
twit|v.嘲笑
very|adv.很,甚,及其,非常,完全adj.真正的,真实的,恰好的,绝对的,十足的,特别的
sheaves|一束
newscast|n.<美>新闻广播
filly|n.小雌马(通常未满四岁),<俚>活泼的小姑娘,<俚>活泼的
compartmentalize|vt.划分
terracotta|n.陶瓦,赤土陶器,赤土色
fly|n.苍蝇,两翼昆虫,飞行vi.飞翔,飘扬,溃逃vt.飞越,使飘扬,逃脱adj.机敏的,敏捷的
reunite|v.(使)再结合
acuity|n.尖锐,(疾病的)剧烈,(视力、才智等的)敏锐
donation|n.捐赠品,捐款,贡献
strangler|扼杀者,压制者
bemuse|vt.使发呆
blasphemy|n.亵渎(话)
envision|vt.想象,预想
lever|n.杆,杠杆,控制杆v.抬起
pasture|n.牧地,草原,牧场v.放牧,牧(牛、羊)等,吃草
vestige|n.遗迹,痕迹,残余,丝毫,[生]退化的器官
shavings|刨花
impermissible|adj.不许可的,不允许的
gross|adj.总的,毛重的n.总额
freckle|n.雀斑,斑点
inflammable|adj.易燃的,易怒的
rubdown|n.擦身,按摩,磨平,磨光
setback|n.顿挫,挫折,退步,逆流,(疾病的)复发
asteroid|n.[天文]小游星,小行星,海盘车adj.星状的
scrawny|adj.瘦脊的,骨瘦如柴的
lighthouse|n.灯塔
feel|vt.摸,触,试探,感觉,觉得,触摸,以为vi.有知觉,(人)有某种感觉,摸索,同情n.感觉,觉得,触摸
linguistics|n.语言学
frown|vi.皱眉,蹙额,不赞成,反对v.皱眉
dank|adj.透水的,潮湿的,阴湿寒冷的
role|n.角色,任务
internally|adv.在内,在中心
malleable|adj.有延展性的,可锻的
coil|v.盘绕,卷
eligible|adj.符合条件的,合格的
secretarial|adj.秘书的,书记的
curb|n.路边
fragmentary|adj.由碎片组成的,断断续续的
asleep|adj.睡着的,睡熟的
ravishing|adj.引人入胜的
frozen|adj.冻结的,冷冰的,冷酷的vbl.freeze的过去分词
phonological|音韵学
methodical|adj.有方法的,有系统的
chatterbox|n.喋喋不休者,唠叨的人
attache|n.<法>大使随员,大使馆专员
bashfulness|
sentimentality|n.多愁善感,感伤癖
Jew|n.犹太人,犹太教徒
bison|n.美洲或欧洲的野牛
cavalry|n.骑兵
parade|n.游行,炫耀,阅兵,检阅,阅兵场v.游行,炫耀,夸耀,(使)列队行进
discrepancy|n.相差,差异,矛盾
sirloin|n.牛的上部腰肉
phial|n.小玻璃瓶,药瓶
sugar|n.糖,食糖
epidemic|adj.流行的,传染的,流行性n.时疫,疫疾流行,(风尚等的)流行,流行病
degradation|n.降级,降格,退化
conciliatory|adj.抚慰的,调和的
formally|adv.正式地,形式上
lactic|adj.乳的,乳汁的
disencumber|vt.摆脱烦恼,不受妨碍
expiation|n.赎罪,补偿
tamper|vi.干预,玩弄,贿赂,损害,削弱,篡改vt.篡改n.捣棒,夯,填塞者
gleanings|n.所拾得的落穗搜集到的情报或新闻
distribute|vt.分发,分配,散布,分布,分类,分区v.分发
wine|n.葡萄酒,酒
provocation|n.激怒,刺激,挑衅,挑拨
pugnacious|adj.好斗的
prestidigitation|n.变戏法
subdued|adj.屈服的,被抑制的,柔和的,减弱的
myopia|n.近视
charm|n.吸引力,(女人的)魔力,魅力,符咒vt.迷人,使陶醉,行魔法vi.用符咒,有魔力
unified|统一的,统一标准的,一元化的
progeny|n.后裔
ultramontane|n.教皇绝对权力主义者,山外之人adj.山那边的
cataclysmic|adj.洪水的,大变动的
world|n.世界,...界,世事,世故,社会adj.世界的
truculent|adj.好战凶猛的
igloo|n.圆顶建筑
culpable|adj.该责备的,有罪的,不周到的
shavings|刨花
malt|n.麦芽
four|num.四,四个,第四(卷,章,叶等)
Christian|n.基督徒,信徒adj.基督教的,信基督教的
conifer|n.[植]松类,针叶树
elite|n.<法>[集合名词]精华,精锐,中坚分子
romantic|adj.传奇式的,浪漫的,空想的,夸大的
swig|n.痛饮,大喝(尤指从瓶口喝的)v.满满一口喝下,牛饮,大喝特喝
adulteration|n.掺杂,掺假货
entertainment|n.款待,娱乐,娱乐表演
technic|n.技术,手法
soy|n.酱油,大豆
pact|n.合同,公约,协定
conductor|n.领导者,经理,指挥管弦乐队、合唱队的,(市内有轨电车或公共汽车)售票员,<美>列车长
eager|adj.热心于,渴望着
dinner|n.正餐,宴会
vocalization|n.发声法
recapture|n.取回,夺回,政府对公司超额收益或利润的征收vt.拿回,夺回,再体验,政府征收再经历,再体验
inimitable|adj.无法模仿的,独特的,无比的
dyslexia|n.[医]诵读困难
perplexity|n.困惑混乱
weaken|v.削弱,(使)变弱
identification|n.辨认,鉴定,证明,视为同一
convoluted|adj.旋绕的,费解的
favoritism|n.偏爱,得宠,偏袒
registration|n.注册,报到,登记
confederate|n.同盟者,同盟国adj.同盟的,联合的vt.vi.(使)联盟,(使)联合,同伙,帮凶
alight|vi.落下adj.点着的,发亮的
carnally|adv.肉体地,世俗地
maximal|adj.最大的,最高的
dismiss|vt.解散,下课,开除,解职,使(或让)离开vi.解散
indulgent|adj.纵容的
queasy|adj.不稳定的
devilish|adj.如恶魔般的,精力旺盛的
cajolery|n.甜言蜜语,诱骗,谄媚
receptor|n.接受器,感受器,受体
handsomely|adv.帅气地,熟练地
exam|n.考试,测验
hotfoot|n.恶作剧adv.急忙地,火急地v.急行
lethal|adj.致命的n.致死因子
inefficient|adj.效率低的,效率差的,(指人)不能胜任的,无能的
slop|v.溢出,溅溢
Australian|adj.澳洲的,澳大利亚的,澳大利亚人的n.[地名]澳大利亚
countess|n.伯爵夫人,女伯爵
undeniable|adj.不可否认的
dermatology|n.皮肤医学,皮肤病学
cane|n.细长的茎,藤条vt.以杖击,以藤编制
general|n.普通,将军,概要adj.一般的,普通的,综合的,概括的,全面的,大体的n.常规
alignment|n.队列,结盟
viscount|n.(英国的)子爵
perplexity|n.困惑混乱
charge|n.负荷,电荷,费用,主管,掌管,充电,充气,装料v.装满,控诉,责令,告诫,指示,加罪于,冲锋,收费
ungenerous|adj.胸襟狭窄的,吝啬的,不充足的
misty|adj.有薄雾的
horrid|adj.恐怖的,令人讨厌的,可怕的
recorder|n.记录员,录音[像]机n.[计]宏录制器,记录器
organ|n.[机]元件,机构,机关,机关报[乐]风琴,管风琴,嗓音[生物]器官
fathom|n.长度单位(6英尺)vt.测量深度,看穿,彻底了解vi.测深,进行探索
unpromising|adj.无前途的,没有希望的
tactical|adj.战术的
flare|n.闪光,闪耀vi.闪光,突然烧起来,闪耀vt.使闪耀,使张开
defence|n.防卫,防卫设备n.[律](被告的)答辩、辩护
daily|adj.每日的,日常的adv.每日,日常地,天天n.日报,<美口>朝来夜去的女佣
doldrums|n.忧郁,赤道无风带
hawthorn|n.山楂
tie|n.带子,线,鞋带,不分胜负,关系,领带,领结,平局vt.系,打结,扎,约束,与...成平局vi.被用带(或绳子等)系住,结合,打结,不分胜负
brutality|n.残忍,野蛮的行为
agreeable|adj.使人愉快的,惬意的,适合的
propel|vt.推进,驱使
tightfisted|adj.吝啬的
privity|n.私下知悉,默契
streamline|adj.流线型的
canteen|n.小卖部,食具箱,饭盒,(军用)水壶
figurehead|n.装饰船头的雕像,破浪神,有名无实的领袖
ineffectiveness|无效
umpteenth|adj.<口>第无数次(个)的
amnesty|n.(尤指对反政府政治犯的)特赦
manifesto|n.宣言,声明
homely|adj.家常的
juicy|adj.多汁的,潮湿的,有趣的,报酬多的
alder|n.[植]桤木
relay|n.驿马,接替,[电工]继电器vt.(消息,货物等)分程传递,使接替,转播vi.得到接替,转播
alarm|n.警报,惊慌,警告器vt.恐吓,警告
grab|v.抢夺,攫取,夺取
defraud|vt.欺骗
dramatize|vt.改编成为戏剧,编写剧本vi.戏剧地表现
masculine|adj.男性的,男子气概的,[语法]阳性的n.男子,男孩
state|n.情形,状态,国家,政府,州adj.国家的,国有的,国营的,州的,正式的,典礼用的vt.声明,陈述,规定
recessionary|adj.(经济)衰退的,衰退期的
partible|adj.可分的
wear|vt.穿,戴v.(～out)磨损,用旧,(～out)穿着
epistemology|n.[哲]认识论
unruly|adj.不受拘束的,不守规矩的,蛮横的,难驾驭的
sable|n.[动]紫貂,黑貂,黑貂皮,丧服adj.黑貂皮的,黑的,昏暗的
star|n.星,恒星,明星,名角
score|n.得分,乐谱,抓痕,二十,终点线,刻痕,帐目,起跑线vt.把...记下,刻划,划线,获得,评价vi.记分,刻痕,得分
humanize|vt.赋予人性,使通人情,教化vi.变为有人性,变为有情,有教化
concerted|adj.商议定的,协定的,[乐]协调的
incite|vt.激动,煽动
arraignment|n.提问,传讯,责难
bifocal|adj.双焦点的
June|n.六月(略作Jun)
abbey|n.修道院,修道士（总称）
verisimilitude|n.似真,逼真
physiologist|n.生理学者
tendinous|adj.[解]腱的
monogamy|n.一夫一妻制,[动]单配偶,单配性
introvert|n.格性内向的人
bereavement|n.(亲人)丧亡
convert|n.皈依者vt.使转变,转换...,使...改变信仰
colonel|n.陆军上校,团长
famish|vt.(常用被动语态)使挨饿,<古>使饿死vi.饥饿,挨饿
niggling|n.过于琐碎的工作,麻烦事adj.为琐事操心的
hutch|n.养小动物的圈栏（尤指兔箱）,笼,茅屋,小舍vt.把...装箱
hysteric|n.歇斯底里症之发作adj.歇斯底里的,过度狂燥的
scotch|浅刻
akin|adj.同族的,类似的
core|n.果核,中心,核心
irreverent|adj.不尊敬的
actuarial|adj.保险精算师的,保险精算的
universally|adv.普遍地,全体地,到处
embedded|adj.植入的,深入的,内含的
gong|n.铜锣,盘形钟vt.打锣作为停车信号
undergo|vt.经历,遭受,忍受
unprofessional|adj.外行的,非职业性的
retort|v.反驳,反击,回报n.曲颈甑,曲颈瓶,蒸器
nephew|n.侄子,外甥
empress|n.皇后,女皇帝,皇太后,极有权力的女人
needy|adj.贫困的,非常贫穷的,缺乏生活必需品的
binding|n.装订,捆绑,捆绑物,粘合物
creditable|adj.可信的
interpose|v.提出
finicky|adj.过分注意的,过分讲究的,过分周到的
excellent|adj.卓越的,极好的
stockily|adv.矮而粗壮地,一本正经地
restriction|n.限制,约束
assistant|n.助手,助教adj.辅助的,助理的
face|n.脸,面容,表情,威信,正面,地形,外观vt.面对,面向,面临,承认,抹盖vi.朝,向
tar|[计]一种压缩文件的扩展名n.焦油,柏油
exponential|n.指数,倡导者,演奏者,例子,[数]指数adj.指数的,幂数的
showdown|n.摊牌
panegyric|n.颂词,推崇备至
moonlighting|n.夜间活动,夜袭,(尤指在夜间)从事第二职业
famished|极饥饿的
grew|vbl.grow的过去式
supernatural|adj.超自然的,神奇的n.超自然物,神奇人物,不可思议的事
pommel|n.(刀剑柄)圆头,(马鞍)前鞍
mistily|adv.有雾地,朦胧地,不清楚地
Muslim|n.穆斯林,穆罕默德信徒
participation|n.分享,参与
prospects|前景
deny|v.否认,拒绝
applause|n.鼓掌欢迎,欢呼
caliper|n.测径器,卡钳,弯脚器vt.用卡钳测量
most|adj.最多的,多数的,大部分的adv.最,最多,很,十分,最,最大的,其中大多数,极其n.大多数,大部分
parole|n.诺言,誓言vt.有条件释放,假释
verbally|adv.用言辞地,口头地
challenger|n.挑战者
psychosomatically|
mincing|adj.装腔作势的v.切碎
instillation|n.灌输,滴,滴下
indulge|v.纵容
heirloom|n.传家宝,相传动产
factually|adv.真实地,确实地
asphyxiate|vi.窒息vt.使窒息
come|vi.来,来临,到达,出现,来(自),出生(于),开始int.嗨!vbl.来,到达,合计为
turn|n.转动,旋转,转变方向,轮流,时机,(一)回,倾向,癖性v.(使)转动,翻转,扭转,(使)变质,超过(年龄,数量等),车(成)
dragnet|n.拖网,搜索网
quadruped|n.四足动物
commodity|n.日用品
melodious|adj.音调优美的
sunken|adj.沉没的,凹陷的vbl.sink的过去分词
checkout|检验,校验
necessary|n.必需品adj.必要的,必需的,必然的
retarded|adj.智力迟钝的,发展迟缓的
algebra|n.代数学
arsenal|n.兵工厂,军械库
spade|n.铲,铁锹v.铲
fiance|n.<法>未婚夫
flagellum|n.[动]鞭毛,鞭子,[植]鞭状匍匐枝
quaff|v.一口气喝干,大口地喝n.一饮而尽,痛饮
ugly|adj.丑陋的,难看的
starry|adj.布满星星的
path|n.小路,小径,路线,轨道,通道
clamp|n.夹子,夹具,夹钳vt.夹住,夹紧
increasingly|adv.日益,愈加
sod|n.草地v.铺草皮于
gratingly|adv.使人急躁地
hospice|n.旅客住宿处,收容所,济贫院
merry|adj.欢乐的,愉快的
advisable|adj.可取的,明智的
banker|n.银行家
lump|n.块（尤指小块）,肿块,笨人vt.使成块状,混在一起,忍耐,笨重地移动vi.结块
culmination|n.顶点
modernization|n.现代化
validate|vt.[律]使有效,使生效,确认,证实,验证
metaphysic|形而上学玄学玄学体系
carol|n.欢乐的歌,颂歌,(尤指)圣诞节颂歌v.歌颂,欢唱
extraordinary|adj.非常的,特别的,非凡的,特派的
ineptitude|n.不称职
playmate|n.玩伴,游伴
cooler|n.冷却器
neglectfully|adv.怠慢地,不注意地
interrogatory|adj.质问的,疑问的n.疑问,质问,质询
vigilance|n.警戒,警惕,失眠症,警惕性
occupant|n.占有者,居住者
chrome|n.铬,铬合金
dye|n.染料,染色vt.染v.染
facile|adj.易做到的,易得到的,不花力气的,敏捷的,流畅的,(性格)柔顺的,温和的,容易的
sonority|n.响亮,响亮程度
popularity|n.普及,流行,声望
handily|adv.方便地
sequent|adj.接续而来的
lathe|n.车床,[纺]走梭板vt.用车床加工
dove|n.鸽子vbl.dive的过去式
duplication|n.副本,复制
orator|n.演说者,演讲者,雄辩家,[律]原告,请愿人
misgive|vi.疑虑vt.使怀疑
pastor|n.牧师
irony|n.反话,讽刺,讽刺之事
manicure|n.修指甲v.修剪
tedious|adj.单调乏味的,沉闷的,冗长乏味的
gripe|n.紧握,柄,把手,控制,苦恼vt.抓紧,抱住,激怒,使苦恼,使肠痛vi.肠痛,抱怨
violoncello|n.大提琴
rateable|adj.可评价的,按比例的
angular|adj.有角的
lustily|adv.精力充沛地,强壮地
illiterate|n.文盲adj.不识字的,没受教育的
sentinel|n.哨兵
liven|v.具有活力
hospital|n.医院
inextricable|adj.无法解脱的,逃脱不掉的,解不开的
authentically|adv.确实地,真正地
cardiac|n.强心剂,强胃剂adj.心脏的,(胃的)贲门的
choreograph|v.设计舞蹈动作
loyally|adv.忠诚
dandify|vt.打扮得时髦
fledged|adj.羽毛丰满的,快会飞的,随时能飞的
confirmed|adj.证实的,惯常的,慢性的
virginal|n.十六,七世纪的小型有键乐器adj.处女的,无瑕的
inadequately|adv.不适当地
magnolia|n.木兰,玉兰类的植物
sophisticated|adj.诡辩的,久经世故的
sweetheart|n.情人,爱人vi.爱慕vt.求爱adj.私下签定的
musicology|n.音乐学
wrestling|n.[体]摔跤
condition|n.条件,情形,环境,社会地位vt.以...为条件,使达到要求的情况
illicit|adj.违法的
gastronomy|n.美食法,烹饪法,享乐主义
brew|v.酿造,酝酿
blaze|n.火焰,光辉,情感爆发vi.燃烧,照耀,激发vt.在树皮上刻路标,公开宣布
self-interest|n.利己主义,私利
incorrigibly|adv.不能矫正地
matriarchy|n.女家长制,女族长制
blot|n.污渍,污点v.弄污
poniard|n.短剑,匕首v.以匕首刺
absentminded|adj.心不在焉的,茫然的,恍惚的
anteroom|n.接待室,前厅
gather|n.集合,聚集vi.集合,聚集,渐增,蹙眉,化脓vt.使聚集,搜集,积聚,推断
finch|n.[动]雀类(如燕雀,金翅雀等)
ligature|n.绷带
intimidating|威吓
optional|adj.可选择的,随意的
nastily|adv.污秽地,不洁地
maim|vt.使残废,使不能工作
squatter|n.蹲着的人vi.涉水而过
constituency|n.(选区的)选民,(一批)顾客,支持者,赞助者
invest|v.投(资),购买(有用之物)～,授予,投资
mechanics|n.(用作单数)机械学、力学,(用作复数)技巧,结构
agitate|v.搅动,摇动,煽动,激动
intimidating|威吓
come|vi.来,来临,到达,出现,来(自),出生(于),开始int.嗨!vbl.来,到达,合计为
mendacious|adj.虚假的,说谎的
rainproof|n.雨衣,雨披adj.防水的
jugular|adj.喉的,颈的,颈静脉的n.颈静脉
rat|n.老鼠
generic|adj.[生物]属的,类的,一般的,普通的,非特殊的
modernization|n.现代化
humus|n.腐殖质
fourteen|num.十四
wilderness|n.荒野,茫茫一片,大量,荒地
discourtesy|n.无礼
bolero|n.(轻快的西班牙)波利乐舞,(轻快的西班牙)波利乐舞曲,一种开口的女用短上衣
reflect|v.反射,反映,表现,反省,细想
pregnancy|n.怀孕
transference|n.移动,转送,转让
presume|vt.假定,假设,认为
huffily|
category|n.种类,别,[逻]范畴
patronage|n.保护人的身份,保护,赞助,光顾
story|n.故事,小说,传说,事迹,经历,假话,谎话
pedal|n.踏板v.踩...的踏板
kilogram|n.[物]千克,公斤
perfectionist|n.十全十美主义者,[哲]至善论者
footlights|n.脚灯,舞台
leakage|n.漏,泄漏,渗漏
whine|n.抱怨,牢骚,哀鸣vi.报怨声,哭诉,发牢骚,发呜呜声vt.哀诉
aerobatics|n.特技飞行,特技飞行术
predict|v.预知,预言,预报
sunstroke|n.[医]日射病,中暑
inscription|n.题字,碑铭
advantage|n.优势,有利条件,利益
comfortably|adv.安乐地,舒适地,充裕地
particular|n.细节,详细adj.特殊的,特别的,独特的,详细的,精确的,挑剔
maudlin|adj.感情脆弱的n.脆弱的感情
drink|n.饮料,酒,酗酒,一口(或一些)饮料v.喝,喝酒,(植物、土壤等的)吸水,举杯庆贺
grin|n.露齿笑,裂口笑v.露齿而笑
mainsheet|n.主桅帆操纵索
violin|n.小提琴,小提琴手
worthwhile|adj.值得做的,值得出力的
degree|n.度数,度,程度,[律](罪行的)轻重,学位,地位,身份,[数]次数
boom|n.繁荣,隆隆声v.发隆隆声,兴隆,大事宣传
wizardry|n.巫术
conventional|adj.惯例的,常规的,习俗的,传统的
atonement|n.赎罪,弥补
fro|adv.往,去,回,向后
cozy|adj.舒适的,安逸的,惬意的
doctoral|adj.博士的
squabble|v.争论
subterranean|adj.地下的
keynote|n.基调
sparing|adj.节俭的,保守的
fatherhood|n.父亲的身份,父性,父权
rationalistic|adj.纯理论的,理性主义的
circumspect|adj.慎重的,周到的
birthday|n.生日
disappointing|adj.使人失望的,令人失望的
naivete|n.天真烂漫,纯真无邪
indefinite|adj.模糊的,不确定的,[语]不定的
watertight|adj.不漏水的,水密的
subtend|v.对向,包在叶腋内
salty|adj.有盐分的,咸味浓的
torturous|adj.拷问的,痛苦的
implode|vi.向内破裂,爆炸
dismount|v.(使)下马
deforestation|n.采伐森林,森林开伐
stipulate|v.规定,保证
trowel|n.泥铲,移植泥刀vt.用泥铲铲,用泥铲涂
low|n.低,低价,牛叫声adj.低的,浅的,消沉的,微弱的,粗俗的,卑贱的,体质弱的adv.低下地,谦卑地,低声地,低价地vi.牛叫
feud|n.不和,(部落或家族间的)世仇,封地,争执vi.长期不和,长期争斗
prosaic|adj.散文的,散文体的,平凡的
lying|n.说谎adj.躺着的,说谎的
latitudinal|adj.纬度的,纬度方向的
clearway|n.超速道路
boll|n.圆荚
enlargement|n.放大
metamorphosis|n.变形
latter|adj.后面的,(两者中)后者的,较后的,近来的
happen|vi.发生,碰巧,偶然v.发生,恰巧,偶然发现
sinewy|adj.强壮有力的
hurling|n.爱尔兰式曲棍球
inquiringly|爱追根究底
animosity|n.仇恨,憎恶
brackish|adj.有盐味的,可厌的
emigrant|n.移居外国者,移民
sprocket|n.链轮齿
weekday|n.周日,平日
tenant|n.承租人,房客,租客v.出租
trivia|n.琐事
neglectfully|adv.怠慢地,不注意地
forgotten|vbl.forget的过去分词
astonish|vt.使惊讶
leaf|n.叶,树叶,(书的)一张(两叶),页vi.生叶,翻书页vt.翻...的页
tempest|n.暴风雨,骚乱,动乱vt.使狂怒,扰乱,使激动vi.起大风暴,小题大作
circumspectly|adv.慎重地,留心地
illusive|adj.(illusory)幻影的,错觉的,迷惑人的,虚假的,不牢靠的
snap|v.猛地吸住,突然折断,使劈啪地晌,猛咬n.猛咬,突然折断,劈啪声adj.突然的
garret|n.顶楼
consolidation|n.巩固,合并
taper|n.锥形,锥度v.逐渐变细,逐渐减少
imprisoning|监禁
hood|n.头巾,兜帽,车蓬,引擎罩v.用头巾包裹,给...加罩,覆盖
lank|adj.瘦的,（树等）细长的,（草等）稀疏的,（头发）平直的
unrelenting|adj.不宽恕的,不屈不挠的,无情的,冷酷的
pretentious|adj.自命不凡的
cabal|n.(政治)阴谋小集团,(尤指政治上的)阴谋vi.策划阴谋
comic|n.滑稽演员adj.滑稽的,喜剧的
variability|n.可变性
marrow|n.髓,骨髓,精华,活力,<苏格兰>配偶
unwittingly|adv.不知情地,无意地
order|n.次序,顺序,正常(工作)状态,秩序,会议规则,命令,定购,定单vt.命令,定购,定制
insurgent|adj.起义的
vivisectionist|n.活体解剖者
volume|n.卷,册,体积,量,大量,音量
slovenly|adj.懒散的,不修边幅的
plural|adj.复数的
synagogue|n.犹太人集会,犹太教会堂,犹太教
xerophyte|n.干燥地带植物
troublesome|adj.麻烦的,讨厌的,棘手的
spiteful|adj.怀恨的,恶意的
headmistress|n.女校长
locale|n.现场,场所
intercept|vt.中途阻止,截取
superabundance|n.多余,剩余,过多
purposeful|adj.有目的的
efficiently|adv.有效率地,有效地
explicit|adj.外在的,清楚的,直率的,(租金等)直接付款的
topography|n.地形学
craftily|adv.狡猾地
authentically|adv.确实地,真正地
rap|n.叩击,轻拍,轻敲,斥责vt.敲,拍,打,厉声说出,斥责,使着迷vi.敲击,交谈abbr.[军]RocketAssistedProjectile,火箭助推炮弹
indefinably|adv.无法下定义地,不明确地
clutch|v.抓住,攫住n.离合器
graveyard|n.墓地
data|n.datum的复数,[计]资料,数据
temporize|v.见风驶舵
concise|adj.简明的,简练的
javelin|n.(投掷用的)标枪
swung|vbl.swing的过去式和过去分词
umpteenth|adj.<口>第无数次(个)的
wand|n.棒,棍,杖,(表示官职的)权杖,(柳树等幼树的)嫩枝
relationship|n.关系,关联
proportional|adj.比例的,成比例的,相称的,均衡的
passe|adj.已过盛年的,凋谢的
coma|n.昏迷
dancer|n.舞女,舞蹈少女
destroy|vt.破坏,毁坏,消灭v.消灭,摧毁
publisher|n.出版者,发行人
induct|v.感应
mood|n.心情,情绪,语气,状态
twiddle|vt.捻起来,抚弄,玩弄,旋弄vi.玩弄n.捻
serendipity|n.有意外发现珍宝的运气
swoop|n.突然下降,猛扑vt攫取vi.飞扑,突然袭击
rawhide|n.生牛皮,<美>生牛皮鞭vt.用生牛皮鞭抽打adj.生牛皮的
indisposed|adj.不舒服的,不合适的
snobbishness|n.势利
shallowness|浅
palliate|v.减轻
polished|adj.擦亮的,磨光的,精练的,优美的,无暇的
lain|vbl.lie的过去分词
flowery|adj.多花的,绚丽的,华丽的,花的,象花一样
promiscuity|n.混乱,杂乱,尤指男女乱交
theorize|v.建立理论,理论化
problematic|adj.问题的,有疑问的
literally|adv.照字面意义,逐字地
introduce|vt.介绍,传入,引进,提出
aliment|n.食物,滋养品
promise|vt.允诺,答应n.允诺,答应,许诺
bonny|adj.漂亮的,健美的
stolid|adj.不易激动的,感觉迟钝的,神经麻木的
dainty|n.适口的食物,美味adj.秀丽的,优美的,讲究的,挑剔的,适口的
qualm|n.疑虑
disrespectfully|无敬意
servant|n.仆人
balk|n.障碍,梁木v.妨碍,(马)不肯前进
steadfast|adj.坚定的
gag|n.塞口物,随口科白,打诨,箝口物,箝制言论,讨论终结vt.塞物于...的口中,禁止,使窒息,使呕吐,压制言论自由,插科打诨,欺骗vi.窒息,作呕,欺骗,插科打诨
far|adj.(常用于书面语)远的,久远的,遥远的adv.(表示空间或时间上的距离)远,很远,遥远地,久远地,甚远地,很,很晚地n.远处,远方
muzzy|adj.头脑发昏的,无精神的,酩酊的
conformance|n.顺应,一致
coop|n.小屋,鸡(兔)笼,拘留所,<俗>监狱vt.关进(鸡舍等),拘禁
franchise|n.特权,公民权v.赋予特权,赋予公民权
acridity|n.辛辣,狠毒
waiter|n.侍者,服务员
numismatic|adj.钱币的,奖章的,钱币学的
celerity|n.敏捷,快速
quota|n.配额,限额
corollary|n.必然的结果,系,推论
drama|n.(在舞台上演的)戏剧,戏剧艺术
antarctic|adj.南极的,南极地带的
vise|n.签证v.签准
turbulence|n.骚乱,动荡,(液体或气体的)紊乱
upper|adj.上面的,上部的
incorporate|adj.合并的,结社的,一体化的vt.合并,使组成公司,具体表现vi.合并,混合,组成公司vt.[律]结社,使成为法人组织
pariah|n.贱民(印度的最下阶级)
philological|adj.语言学的,文献学的
integrate|vt.使成整体,使一体化,求...的积分v.结合
divagate|v.流浪,漫游,离题
millennium|n.太平盛世,一千年
hang|n.悬挂的方式,（动作的）暂停,中止vt.悬挂,附着,装饰,绞死,踌躇,使悬而未决,垂下vi.悬着,垂下,被绞死,悬而不决
sheep|n.羊,绵羊,羞答答的人,胆小鬼,信徒
frequently|adv.常常,频繁地n.经常地
indeed|adv.真正地,(加强语气)确实,(表示让步)当然,甚至,真的吗?
womanly|adj.像女人的,有女子气质的
shelter|n.掩蔽处,身避处,掩蔽,保护,庇护所,掩体v.掩蔽,躲避
liveable|adj.适于居住的,可住的
subjugation|n.镇压,平息,征服
gastronomic|adj.美食(烹饪)法的,烹任学的
deputize|v.代表
dynamic|adj.动力的,动力学的,动态的
cavort|vi.腾跃
core|n.果核,中心,核心
transatlantic|adj.大西洋彼岸的
accoutrements|n.军人的配备,服装
quietus|n.偿清,解除,寂灭,死
genre|n.类型,流派
shelves|n.架子
off|adj.远的,空闲的,不工作的adv.离开,在远方,离去,分离,中断,完成prep.从...离开,脱离
play|n.游戏,比赛,运动,赌博,剧本v.玩,扮演,播放,进行比赛v.播放
liberation|n.释放,解放
pulsate|vi.搏动,跳动,有规律的跳动
sable|n.[动]紫貂,黑貂,黑貂皮,丧服adj.黑貂皮的,黑的,昏暗的
affirmative|adj.肯定的,(对正式辩论中的问题)表示赞成的,(态度,方法等)积极的,乐观的,怀有希望的n.肯定语
gullibly|
proverbially|adv.如谚语所说的,众所周知的
gerontocracy|n.老人统治,老人政治,老人政府
deterrent|n.威慑
cynosure|n.小熊座,北极星
sixtieth|num.第六十,六十分之一
obscured|遮蔽
alliterate|v.用头韵体作,押头韵
campanology|n.鸣钟术,铸钟术
desiccation|n.干燥
eyewash|n.洗眼水,<俚>胡话,空话,拍马,奉承,骗局,表面文章
palette|n.调色板,颜料
road|n.路,道路,公路,大道
premeditate|v.预谋,预先考虑
senate|n.参议院,上院
another|adj.另外的,又一,不同的prep.另一个,另一个人,同类的东西
illiberally|adv.吝啬地,小气地
plus|prep.加上adj.正的,加的
strontium|n.锶
tensile|adj.可拉长的,可伸长的,[物]张力的,拉力的
sense|n.官能,感觉,判断力,见识,...感,意义,理性vt.感到,理解,认识
absolutely|adv.完全地,绝对地
nib|n.嘴,鹅管笔的尖端,钢笔尖vt.装尖头,削尖,插入
auxiliary|adj.辅助的,补助的
pool|n.池,撞球,联营,石油层vt.合伙经营,共享,共有,集中(钱、力量等),采掘,汇聚成vi.汇合成塘,郁积,联营
downgrade|n.下坡,退步adj.下坡的,使降级,小看
diagrammatically|图解表示
prologue|n.序言
modernism|n.现代风,现代主义,现代思想
customer|n.消费者
penalize|v.处罚
cannibalism|n.嗜食同类,食人,自相残杀，人吃人的
flexibility|n.弹性,适应性,机动性,挠性
tomorrow|adv.明天见n.明天,未来
kilobyte|n.〈计〉千字节，1024字节
inchoate|adj.未形成的,早期的,不完全的
tyrant|n.暴君
brilliance|n.光辉,显赫,鲜明
tail|n.尾部,尾巴,尾状物,后部,(常用复数)(硬币)反面辫子,踪迹,排的长队,限定继承权adj.在后面的,从后面而来的,限定继承的,尾部的,后面来的,后部的vt.为...装尾,附于其后,尾随,跟踪,使搭牢,监视,使架住vi.成为散乱的行列,跟踪,嵌入,船尾搁浅
jealous|adj.妒忌的,猜疑的,警惕的,嫉妒的
ornithologist|n.鸟类学者
snazzy|adj.时髦的
multiply|v.繁殖,乘,增加
derelict|adj.被抛弃了的n.遗弃物
penumbra|n.[天]（日蚀、月蚀或太阳黑子的）半影
invidious|adj.易招嫉妒的,不公平的,诽谤的
boy|n.男孩,儿子,孩子气的人,男仆
furnish|vt.供应,提供,装备,布置v.供给
bonus|n.奖金,红利
wizardry|n.巫术
roll|adj.滚动,滚转,(使)摇摆,(使)摇晃,卷起,卷拢vt.辗,轧n.(一)卷,卷形物,摇晃,摆动,名单
Xerox|施乐复印机（商标名称）
know|v.知道,了解,认识,熟悉,认出,分辨,确信
disavow|vt.不承认,否认,否定,抵赖
inquest|n.审讯
complementary|adj.补充的,补足的
choose|v.选择,选定
partake|vt.分担,共享vi.共享,参与,带有
plaudit|n.喝采
eminent|adj.显赫的,杰出的,有名的,优良的
contraband|n.违法交易,违禁品,走私adj.禁运的,非法买卖的
hydroelectric|adj.水力电气的
aerostat|n.航空器
jocularity|n.滑稽,戏谑,打趣
circumscribe|vt.在...周围画线,限制
police|n.警察队,警察机关,公安部门vt.管辖,维持治安adj.警察的,有关警察的
tauten|v.拉紧
hominid|n.原始人类
front|n.前面,开头,前线,(政治上的)阵线,态度,外表vt.面对,朝向,对付vi.朝向
obsequies|n.葬礼
acerbic|adj.酸的,尖刻的
handout|n.分发的印刷品,新闻稿
hopeful|adj.怀有希望的,有希望的
cereal|n.谷类食品,谷类
cosmogony|n.宇宙的产生,宇宙进化论
goldbrick|vi.称病,欺诈,偷懒n.假金砖,懒汉,赝品
underhand|adj.秘密的,下投的,欺瞒的adv.秘密地,阴险地,(打球时)手不过肩地
extremity|n.末端,极端,极度,穷困,绝境,临死,非常手段,手足
stupid|adj.愚蠢的,麻木的,乏味的
exactitude|n.正确,精密,精确,严格,规规矩矩
headstone|n.墓石,基石
rheumatism|n.风湿,风湿病
unfathomable|adj.深不可测的,无底的,难解的
hop|v.单脚跳,(鸟,蛙等)跳跃n.蛇麻草
bygone|n.过去的事adj.过去的
hypocrisy|n.伪善
heartiness|n.诚实,热心
verbally|adv.用言辞地,口头地
sprinkler|n.洒水车,洒水装置
quickie|n.<俚>匆匆做成的事,快饮adj.<俚>简短的,速成的
train|n.火车,列车,行列,后果,顺序,长队,长袍(裙)拖地的部分,导火线vt.训练,培养,瞄准,(园艺)整枝vi.锻炼
blasphemer|n.亵渎者,辱骂者
discordant|adj.不调和的,不和的,[乐]不悦耳的,不和谐的
metre|n.米,公尺
umbrella|n.伞,雨伞,庇护
inhabitant|n.居民,居住者
unstudied|adj.非娇揉造作的,未学过的,不懂的
bad|adj.劣质的,有害的,坏的,不利的,不健康的,严重的
tension|n.紧张(状态),不安,拉紧,压力,张力,牵力,电压vt.拉紧,使紧张
misunderstanding|n.误会,误解
ornithology|n.鸟类学,鸟学论文
forest|n.森林,林木,<英>御猎场adj.森林的,住在森林中的vt.植树于
flame|n.火焰,光辉,光芒,热情,激情
survive|v.幸免于,幸存,生还
objectionably|引起反对
mockery|n.嘲笑
potpourri|n.花香,肉菜杂烩
drought|n.干旱,缺乏
thread|n.线,细丝,线索,思路,螺纹
arboreal|adj.树的,乔木的,树栖的
hybrid|n.杂种,混血儿,混合物adj.混合的,杂种的
efflorescence|n.开花,[化]风化
probation|n.试用,见习,鉴定,查验,证明,察看,缓刑
beside|prep.在旁边,和...比较
wiliness|n.狡猾
pristine|adj.质朴的
stuff|n.原料,材料,素材资料vt.塞满,填满,填充
chargeable|adj.可以控诉的,可记在某项帐目上的,可充电的
cinema|n.电影院,电影
comedy|n.喜剧,喜剧性的事情
intestinal|adj.肠的,肠内的,(疾病)侵袭肠的
encroachment|n.侵蚀,侵犯
classmate|n.同班同学
dissociate|v.分离,游离,分裂
prescriptive|adj.说明性的
payoff|n.发工资,付清,盈利,<口>(故事等的)高潮,报应,贿赂adj.决定性的
fracture|n.破裂,骨折v.(使)破碎,(使)破裂
reason|n.理由,原因,动机,理智,前提vt.说服,推论,辩论vi.推论,劝说,思考
shrink|v.收缩,(使)皱缩,缩短
knickknack|n.小玩意儿
ablution|n.清洗
gruelling|使人精疲力尽
onerous|adj.繁重的,费力的,负有法律责任的
against|prep.相反,反对,逆着,靠着,倚着
clampdown|n.压制,取缔
upfront|adv在前面，在最前面
chagrin|n.懊恼,气愤,委屈
palpably|adv.可触知地,易觉察地
axle|n.轮轴,车轴
psych|vt.使...激动,用心战击败
edify|v.启发
gibbon|n.长臂猿
denial|n.否认,否定,谢绝,拒绝
self-taught|adj.自学而成的,自修的
widening|加宽,扩展
abbey|n.修道院,修道士（总称）
estancia|n.(拉丁美洲的)大牧场大庄园
chest|n.胸腔,胸膛,箱,柜
unexampled|adj.无前例的,无可比拟的
detrimentally|adv.有害地,不利地
fearfully|adv.颇,非常地,极
petulant|adj.脾气坏的,使性子的
chary|adj.仔细的,谨慎的,吝啬的
outskirts|n.边界,(尤指)市郊
lugubrious|adj.（尤指故意装出来的）可怜的,悲惨的,悲哀的
concurrent|n.同时发生的事件adj.并发的,协作的,一致的
will|n.意志,决心,意向,遗嘱v.aux.将,愿意,必须
paradox|n.似非而是的论点,自相矛盾的话
recessionary|adj.(经济)衰退的,衰退期的
seashore|n.海岸,海滨
birthrate|n.出生率
sanction|n.批准,同意,支持,制裁,认可v.批准,同意,支持,鼓励,认可
precariously|不稳定
suburbanize|使成[变]为市郊市郊化
unscrupulous|adj.肆无忌惮的,无道德的,不谨慎的
knight|n.(欧洲中世纪的)骑士,爵士,武士vt.授以爵位
paragraph|n.(文章)段,节,段落
epicycle|n.[天]本轮,[数]周转圆
bump|n.撞击,肿块v.碰(伤),撞(破),颠簸
himself|pron.他自己,他亲自
chalet|n.瑞士山中的牧人小屋
thirst|n.渴,口渴,(～for)渴望,热望
snare|n.陷井v.诱捕
fate|n.天数,命运,运气vt.注定,送命
harem|n.（伊斯兰教教徒之）闺房,闺房里的妻妾群,为一个雄性动物所控制的许多雌性动物
berry|n.浆果
petroleum|n.石油
permanent|adj.永久的,持久的
overhear|vt.无意中听到,偷听
misunderstand|vt.误解,误会
offshoot|n.分支,支流
fitful|adj.断断续续的,一阵阵的,间歇的,不定的,不规则的
teammate|n.队友
psych|vt.使...激动,用心战击败
fatten|vi.长肥,(靠...)发财,养肥vt.养肥,使肥沃,使充实,使肥胖
avowal|n.声明
far|adj.(常用于书面语)远的,久远的,遥远的adv.(表示空间或时间上的距离)远,很远,遥远地,久远地,甚远地,很,很晚地n.远处,远方
foully|adv.下流地,卑鄙地
circulation|n.循环,流通,发行额
gloat|v.心满意足
ambivalence|n.正反感情并存
backbreaking|adj.非常辛劳的
villager|n.村民
steadily|adv.稳定地,有规则地
unstudied|adj.非娇揉造作的,未学过的,不懂的
twiggy|adj.多细枝的,小枝繁茂的
sap|n.树液,体液,活力,坑道,笨人,傻子vt.使排出体液,使衰竭,挖坑道袭击,逐渐侵蚀vi.挖坑道
confide|v.倾诉,委托,信赖
fat|n.脂肪,肥肉adj.肥大的,丰满的,肥的,胖的,油腻的n.文件分配表vt.养肥,在...中加入脂肪vi.长肥
particularity|n.特性
skillfulness|熟练
Zionism|犹太复国主义
delinquent|n.失职者,违法者adj.失职的,有过失的,违法的,拖欠债务的
perennially|adv.永久地
cleaner|n.清洁工人,清洁器
outweigh|v.在重量(或价值等)上超过
morale|n.士气,民心
milkman|n.售奶工人,送奶工人
emanate|vi.散发,发出,发源vt.[罕]发散,放射
magnanimous|adj.宽宏大量的,有雅量的
tranquilly|adv.安静地,平静地
fuzzy|adj.有绒毛的,模糊的,失真的
specialize|vi.专攻,专门研究,使适应特殊目的,使专用于
Hebrew|n.希伯来人
bulletin|n.公告,报告
tamper|vi.干预,玩弄,贿赂,损害,削弱,篡改vt.篡改n.捣棒,夯,填塞者
tangibly|adv.可触摸的,可触知地,明白地
apologize|vi.道歉,辩白
conscientiously|adv.良心上
fairyland|n.仙境,乐园,奇境
proposition|n.主张,建议,陈述,命题
herbivorous|adj.食草的
explicit|adj.外在的,清楚的,直率的,(租金等)直接付款的
enact|vt.制定法律,颁布,扮演
nitpick|
powder|n.粉,粉末,火药,尘土vt.搽粉于,撒粉,使成粉末vi.搽粉,变成粉末
bluff|n.断崖,绝壁,诈骗adj.绝壁的,直率的vt.vi诈骗
rightly|adv.端正地,正当地,正确地,公正地,恰当地
said|vbl.say的过去式和过去分词adj.上述的
alphabetically|adv.按字母顺序地
medallion|n.大奖章
traditional|adj.传统的,惯例的,口传的,传说的
title|n.头衔,名称,标题,冠军,资格,字幕,权利,扉页vt.赋予头衔,加标题于adj.标题的,用作书名的
gentleness|n.温顺,亲切,柔和
environmentalist|n.环境保护论者,环境论者,环境论信奉者
reluctantly|adv.不情愿地,嫌恶地
constitute|vt.制定(法律),建立(政府),组成,任命
illegible|adj.难辨认的,字迹模糊的
entrance|n.入口,门口,进入
manner|n.礼貌,风格,方式,样式,习惯
nip|n.捏,夹,(寒冷等)刺骨,小饮vt.捏,夹,冻伤,剪断,阻止vi.夹,捏,刺骨,小饮,(口语)急忙
blackout|n.灯火管制,(暂时的)眩晕,中断
swirling|旋涡涡流
out-and-out|adj.完全的,彻底的
heck|n.饲草架
sylvan|n.森林之神,有森林的
concussed|adj. 有脑震荡的
transcript|n.抄本
crabbed|adj.乖戾的,易怒的,难懂的,潦草的
expeditious|adj.迅速的,敏捷的
humanly|adv.像人地,用人力
sedimentation|n.沉淀,沉降
drank|vbl.drink的过去式
intelligibly|adv.易理解地
fig|n.[植]无花果,无花果树,无价值的东西,少许,一些,服装vt.打扮,使马跑快
discomfiture|n.挫折,失败,崩溃,尴尬
dismal|adj.阴沉的,凄凉的,暗的vt.使人消沉n.低落的情绪,沼泽
visually|adv.在视觉上地,真实地
strike|n.罢工,打击,殴打vt.打,撞击,冲击,罢工,打动,划燃,到达,侵袭vi.打,打击,罢工,抓,敲,搏动,打动,穿透
crystallize|v.明确
lavishly|adv.浪费地,丰富地
moat|n.护城河,城壕v.挖壕围绕
tenacity|n.坚韧
pool|n.池,撞球,联营,石油层vt.合伙经营,共享,共有,集中(钱、力量等),采掘,汇聚成vi.汇合成塘,郁积,联营
downtrodden|adj.被践踏的,被蹂躏的,被压制的
razzle|n.眼花缭乱,喧闹,旋转木马
bookmark|n.书签
stardom|n.演员的身份,演员们
musician|n.音乐家
asymmetrical|adj.不均匀的,不对称的
monitory|adj.训诫的n.告戒书
handpicked|adj.用手挑选的,精选的,凭个人挑选的,偏心挑选的
self-taught|adj.自学而成的,自修的
usurper|n.篡夺者,篡位者
sparingly|adv.节俭地,保守地
rootless|adj.无根的,无根据的
ballot|n.选举票,投票,票数vi.投票
reluctance|n.不愿,勉强
press|n.压,按,印刷,压力,拥挤,紧握,新闻vt.压,压榨,紧抱,逼迫vi.压,逼迫,拥挤,受压
hydra-headed|多头
flowchart|流程图,程序框图,操作程序图,生产过程图解
convertible|adj.可改变的,自由兑换的
neglectful|adj.忽略的
sexy|adj.有性感的,色情的,迷人的
self-confidence|n.自信
lusty|adj.健壮的,精力充沛的
prediction|n.预言,预报
egalitarian|adj.平等主义的n.平等主义
prominently|adv.显著地
unstintingly|
lighten|v.减轻,(使)轻松,(使)发亮,照
coinage|n.造币,货币制度,创造,新造的字及其语等
downtown|adv.在市区,往市区adj.市区的
misappropriate|v.盗用
precipitous|adj.陡峭的,急躁的
trend|n.倾向,趋势vi.伸向,倾向,通向
mutterer|
forger|n.伪造者,铁匠,赝造者
dialectically|
interrogation|n.审问,问号
prevalence|n.流行
trepidation|n.颤抖
forfeiture|n.丧失,没收物,罚款
bookseller|n.书商
him|pron.他
mission|n.使命,任务,使团,代表团
acrimony|n.言谈举止上的刻毒,讽刺,毒辣
awaken|v.唤醒,醒来,唤起
circumvention|n.陷害,欺骗
tribal|adj.部落的,种族的
girdle|n.带,腰带,带状物,浅锅v.束,绕,包围,围绕
dorsal|adj.背的,脊的
marijuana|n.[植]大麻n.[植]大麻,大麻干叶和花
photocopier|n.影印机
rend|v.撕碎
astonished|惊讶的
cringe|vi.畏缩,阿谀,奉承
acumen|n.敏锐,聪明
capillary|n.毛细管adj.毛状的,毛细作用的
masked|v.伪装adj.戴面具的
plagiarize|v.剽窃,抄袭
uncommunicative|adj.拘礼的,沉默寡言的
preoccupation|n.当务之急
croak|n.蛙或鸦的叫声vi.嗄嗄叫,发牢骚vt.用嘶哑的声音说
balky|adj.停止不前的,倔强的,执拗的
fig|n.[植]无花果,无花果树,无价值的东西,少许,一些,服装vt.打扮,使马跑快
recreate|v.(使)得到休养,(使)得到娱乐
galore|adv.丰富地
goad|n.(赶牲口用的)刺棒,激励物,刺激物vt.用刺棒驱赶,驱策,激励,刺激,唆使,煽动
geometrically|adv.用几何学,几何学上
pungency|n.苦痛,辛辣,刺激,尖刻
stealthy|adj.鬼鬼祟祟的,秘密的,掩人耳目的
Tory|n.保守党党员,保皇党人adj.保守分子的
legislate|vi.制定法律vt.通过立法
navigate|vi.航行,航海,航空vt.航行于,驾驶,操纵,使通过
priory|n.小修道院
succubus|n.女妖,妓女,魔鬼
perennial|adj.四季不断的,终年的,长期的,永久的,(植物)多年生的
bit|n.小块,少量,片刻,马嚼子,辅币vt.上马嚼子,控制vbl.咬n.[计]位,比特
bathetic|adj.平庸的,陈腐的,顿降的
heedless|adj.不注意的
adj|adj.
culmination|n.顶点
incoercible|adj.不可强迫的,不能压制的
freshman|n.新生,大学一年级学生
welsh|vi.不付赌金而溜掉,逃避履行义务,食言vt.逃避(责任等),对(某人)食言adj.威尔士的n.威尔士人
utilization|n.利用
essentially|adv.本质上,本来
consummate|vt.完成,使达到极点adj.圆满的,至上的,完美的
grill|n.烤架,铁格子,烤肉v.烧,烤,严加盘问
obstruct|v.阻隔,阻塞,遮断(道路、通道等)n.阻碍物,障碍物
children|n.孩子,孩子们
agitated|adj.激动的,表现不安的
astrophysics|n.天体物理学
stubbornness|n.倔强,顽强
metrical|adj.测量的,度量的,(诗的)韵律的
canoe|n.独木舟,轻舟
entitled|有资格的
gainsay|v.否认
effuse|v.涌出,流出,泻出
vitality|n.活力,生命力,生动性
corduroy|n.灯芯绒,灯芯绒裤子
capriciousness|反复无常
coverage|n.覆盖
delectably|
bitterly|adv.苦苦地,悲痛的,厉害的
hernia|n.[医]疝气,脱肠
subtly|adv.敏锐地,精细地,巧妙地
disdain|n.轻蔑,以高傲的态度对待vt.蔑视,鄙弃
lesson|n.功课,(一节)课,课程,教训
out-of-the-way|adj.偏僻的,偏远的,非凡的,少有的
supernumerary|n.定额以外的人,临时雇工
miter|n.主教法冠
chaste|adj.贞洁的,(思想,言论,尤其是性的节操)有道德的,朴素的
trig|adj.潇洒的
mace|n.钉头,权杖,肉豆蔻,肉豆蔻树,豆蔻香料,催泪瓦斯,肉豆蔻皮
enlightenment|n.启迪,教化
strangle|v.扼死
separable|adj.可分离的,可分的
strangler|扼杀者,压制者
muzziness|酩酊,迷惑,迟钝
whimsical|adj.反复无常的,古怪的
indubitably|adv.无疑地,确实地
bash|v.怒殴,打坏,<美俚>盛会,狂欢n.怒殴,猛击
bard|n.吟游诗人
fretful|adj.烦燥的,起波纹的,焦躁的
hydrous|adj.含水的
weather-beaten|adj.饱经风霜的,风雨侵蚀的
important|adj.重要的,重大的,有权力的,有地位的
urbane|adj.彬彬有礼的,文雅的
freshwater|n.淡水(不是海洋水的),湖水,内河
throve|vbl.thrive的过去式
stainless|adj.纯洁的,无瑕疵的,不锈的
warhead|n.弹头
constitution|n.宪法,构造,体质,体格,国体,章程,惯例
glamour|n.[亦作glamor]魔力,魅力v.迷惑
resourceful|adj.资源丰富的,足智多谋的
stylish|adj.时髦的,漂亮的,流行的
stagnation|n.停滞
half-baked|adj.半生不熟的,未完成的,不完整的
tread|n.踏,步态,梯级,踏板,轮胎面,交尾,鞋底vi.踏,行走,踩碎,践踏,交尾vt.踩,踏,践踏,跳
vainness|n.无益
contractor|n.订约人,承包人
prism|n.[物]棱镜,[数]棱柱
amber|n.琥珀adj.琥珀制的,琥珀色(黄色)的
ripen|vt.使成熟vi.成熟
burgess|n.英国从城市或大学选出的议员
sweater|n.厚运动衫,毛线衫
confessor|n.自白者,为信教而被迫害的教徒
vast|adj.巨大的,辽阔的,大量的,巨额的
repaid|vbl.repay的过去式和过去分词
oblivious|adj.遗忘的,忘却的,健忘的
goodish|adj.尚好的,相当好的,颇的
ape|n.猿
passionate|adj.充满热情的
retardant|n.延缓(作用)剂adj.延缓的,使迟滞的
fuzz|n.细毛,绒毛,警员vi.变成绒毛状,作绒毛状飞散vt.起毛,使模糊
couch|n.(文学)床,睡椅v.(用语言)表达
aberrant|adj.异常的
inland|adj.内陆的,国内的adv.在内地,向内地n.内地
postdate|vt.填迟...的日期n.事后日期
dulcet|adj.愉快的,美妙的,悦耳的,<古>美味的,有香味的
highland|n.高地,丘陵地带
decadent|adj.颓废的n.颓废者
remoteness|n.远离,遥远
harden|vt.使变硬,使坚强,使冷酷vi.变硬,变冷酷,涨价
mighty|n.有势力的人adj.有势力的,强大的,有力的adv.很,极,非常
sumo|n.(Jap.)相扑
requisition|n.正式请求,申请,需要,命令,征用,通知单vt.征用,要求
strategy|n.策略,军略
terminological|adj.术语学的,专门名词的
reconstruct|v.重建,改造,推想
dissimulate|v.掩饰,假装,装糊涂
softball|n.垒球运动,垒球
happy-go-lucky|adj.逍遥的,随遇而安的adv.完全偶然地
seaward|adj.朝海的,海那一边的adv.向海,向海那一边
smoulder|v.潜伏
woven|vbl.weave的过去分词n.机织织物
drastic|adj.激烈的,(药性等)猛烈的
amusement|n.娱乐,消遣,娱乐活动
disfranchisement|n.剥夺公民权
aggrandize|vt.增加,夸大
desperate|adj.不顾一切的,拚死的,令人绝望的
intermittent|adj.间歇的,断断续续的
sacking|n.口袋布,制袋子用的粗麻布,帆布
invest|v.投(资),购买(有用之物)～,授予,投资
radiate|vt.放射,辐射,传播,广播vi.发光,辐射,流露adj.有射线的,辐射状的
nauseous|adj.令人作呕的,厌恶的
parole|n.诺言,誓言vt.有条件释放,假释
adverb|n.副词
inoculation|n.接木,接种,接插芽
imagine|vt.想象,设想
deter|v.阻止
diatomic|adj.二原子的,二氢氧基的,二价的
bandit|n.强盗
dustman|n.清洁工
incompressible|adj.不能压缩的
strangler|扼杀者,压制者
overseas|adv.海外adj.外国的,海外的
dehumanize|v.使失掉人性,使成兽性
incubate|vt.孵卵
rebus|n.(猜字的)画谜
tangent|adj.接触的,切线的,相切的,离题的n.切线,[数]正切
memorably|adv.值得纪念的,重大的,有影响的
wood|n.木头,木材,树木
clandestine|adj.秘密的
yokel|n.庄稼汉,乡下人
captious|adj.吹毛求疵的,挑剔的
mediate|v.仲裁,调停,作为引起...的媒介,居中调停
expanding|adj.展开的,扩大的
transmutable|adj.可变形的
pick|n.精选,掘,鹤嘴锄vt.摘,掘,凿,挑选,挖,挑剔vi.摘,掘,凿,挖,挑选v.拾取
niggle|vi.为琐事费心,拘泥小节vt.小气地给...
fashionableness|
breadth|n.宽度,(布的)幅宽,(船)幅
preview|n.事先查看,[计]预览vt.事先查看,预展,预演
distemper|n.大瘟热,不高兴,病异状vt.用胶画颜料画,使发狂
subsidize|v.资助,津贴
stupendous|adj.惊人的,巨大的
chirp|n.喳喳声,唧唧声v.吱喳而鸣,尖声地说
rightfully|adv.正直地,正当地
steward|n.(轮船,飞机等)乘务员,干事
purblind|adj.半盲的,惺松眼的,迟钝的vt.使成半瞎
viral|adj.滤过性毒菌的,滤过性毒菌引起的
repine|v.抱怨
paleontologist|n.古生物学者
magnetic|adj.磁的,有磁性的,有吸引力的
remit|vt.宽恕,赦免,免除,缓和,推迟,汇出,传送,使复职vi.缓和,汇款n.移交的事物
straggle|v.迷路,落伍,蔓生,四散,漫延n.散乱
stutter|n.口吃,结结巴巴v.口吃着说
ran|vbl.run的过去式
inanimate|adj.死气沉沉的,没生命的,单调的
marsh|n.湿地,沼泽,沼泽地
irreconcilably|
entree|n.入场许可,<英>两道正菜间的小菜,<美>主菜
diatribe|n.恶骂,诽谤
preferment|n.优先
ferromagnetic|adj.铁磁的,铁磁体
toffee|n.太妃糖,胡说,中褐色
pipeline|n.管道,传递途径
estimate|v.估计,估价,评估n.估计,估价,评估
submerge|v.浸没,淹没,掩没vi.潜水
duration|n.持续时间,为期
enthusiast|n.热心家,狂热者
aromatic|adj.芬芳的
valedictorian|n.致告别辞者,告别演说者
sultriness|n.闷热,纵情声色
homesickness|思乡病
bystander|n.看热闹的人,旁观者
chronicle|n.编年史v.编入编年史
infiltrator|n.渗透者,渗入者
function|n.官能,功能,作用,职责,典礼,仪式,[数]函数vi.(器官等)活动,运行,行使职责
suppression|n.镇压,抑制
unessential|adj.非本质的
foray|vt.<古>劫掠vi.袭击n.袭击
discount|n.折扣
equidistant|adj.距离相等的,等距的
insensitive|adj.对...没有感觉的,感觉迟钝的
vexation|n.恼怒,烦恼,着急,苦恼的原因
highway|n.公路,大路
intellect|n.智力
pounce|v.突袭n.突袭
discombobulate|vt.使混乱,使泄气,使困惑
pebbly|adj.多卵石的,有卵石花纹的
imperious|adj.专横的
craziness|n.发狂,热中,狂热
disillusioning|失望
amortize|v.分期清偿
archaeologist|n.考古学家
howl|v.嚎叫,怒吼,嚎啕大哭,喝住,号叫n.嚎叫,怒号,嚎哭
recalcitrance|n.反抗,顽抗
sharpness|n.锐利
hydrant|n.消防栓,消防龙头
appurtenance|n.附件,附属物,[律]从属权利
proverbial|adj.谚语的,谚语式的,众所周知的,公认的
singe|v.烧焦,烤焦
indicative|adj.(～of)指示的,预示的,可表示的
telegraph|n.电报机,电报v.打电报,发电报,打电报说
stipulation|n.约定,约束,契约
dregs|n.渣滓,糟粕
dragoon|n.骑兵,凶暴粗野的男人vt.以武力迫害,弹压,强制
oversea|adj.外国的,海外的
alter|v.改变
supernaturally|adv.超自然地
flaccidity|n.软弱,没气力
exploitation|n.开发,开采,剥削,自私的利用,宣传,广告
hedge|n.树篱,障碍物v.用树篱围住,避免作正面答复
poet|n.诗人
whisky|n.威士忌酒adj.威士忌酒的
tulip|n.[植]郁金香,郁金香花,郁金香球茎
defilement|n.弄脏,污辱,污秽
partisanship|n.党派性,党派偏见
crosscheck|n.多方面求证,反复查对
multiplication|n.[数]乘法,增加,(动,植的)繁殖,增殖
parquetry|n.镶花木细工,镶木地板
goody|n.身份低微之老妇,媪,糖果adj.感伤的,<俗>伪善的int.<俗>好呀！
freshman|n.新生,大学一年级学生
leave|n.许可,同意,请假,休假vt.离开,动身,剩下,遗忘,委托,遗弃vi.出发,离开,生叶,动身
bluster|v.风狂吹,咆哮,吓唬n.怒号,吓唬
overturn|n.倾覆,破灭,革命vt.推翻,颠倒vi.翻倒n.翻转,毁灭
malady|n.疾病
reckoning|n.计算,帐单,算帐,结帐,清算,估计
zone|n.地域,地带,地区,环带,圈vt.环绕,使分成地带vi.分成区
interrelate|v.(使)相互关连
penetrate|vt.穿透,渗透,看穿,洞察vi.刺入,看穿,渗透,弥漫
terminal|n.终点站,终端,接线端adj.末期,每期的,每学期的
conceal|vt.隐藏,隐蔽,隐瞒v.隐蔽
arboretum|n.树园,植物园
trial|n.试验,考验,审讯,审判
sacrilege|n.冒渎,亵渎圣物,悖理逆天的行为,渎圣罪
enkindle|vt.点燃,使燃烧,激起(热情等),挑起(战争等)
sprung|vbl.spring的过去式及过去分词
appreciably|adv.略微,有一点
chubbiness|n.圆胖,丰满
affable|adj.和蔼可亲的
douse|vt.插入水中,把弄熄,弄湿,放松vi.浸泡n.泼洒
beget|vt.(书面语)招致,产生,引起
pickax|n.镐
between|prep.在...之间,连接...,由...协力合作
plenary|adj.(指权力)无限的、绝对的,(指会议)全体出席的,充分的,完全的
recrimination|n.揭丑,反责
diagrammatic|adj.图表的,概略的
prematurely|adv.过早地,早熟地
joy|n.欢乐,喜悦,快乐,乐事,乐趣v.高兴
houseclean|v.扫除,整顿
bemused|adj.困惑的,发呆的
deliverance|n.释放,意见,判决
yell|vi.大叫,忍不住笑,呼喊vt.叫着说n.叫声,喊声
interment|n.埋葬,葬礼
odorous|adj.有气味的
abruptly|adv.突然地,唐突地
acclivity|n.[地]向上的斜坡
hair|n.头发,毛发,毛状物,绒毛,些微
shuffler|
indecisiveness|非决定性
joviality|n.快活
hexapod|n.昆虫,六脚的节足动物adj.六脚的
winsome|adj.迷人的
opinion|n.意见,看法,主张,判断,评价
tactless|adj.不老练的
viceroy|n.总督
rudder|n.舵,方向舵
cognate|adj.同词源的,同类的
humility|n.谦卑
hardback|n.硬封面的书
rousing|adj.鼓舞人的,活跃的,非凡的
lift|n.举起,电梯,起重机,搭车vt.升高,提高,举起,空运vi.升起,(指雾等)消散,耸立
swath|n.收割的刈痕,细长的列
vigilant|adj.警惕着的,警醒的
dialogue|n.对话
airforce|n.空军
typist|n.打字员
miniature|n.缩小的模型,缩图,缩影adj.微型的,缩小的
perpendicularly|adv.垂直地,直立地
ukraine|n. 乌克兰（原苏联一加盟共和国，现已独立）
racially|adv.按人种,人种上
stain|n.污点,瑕疵v.染污,沾污
sell|v.出售,卖
atone|v.弥补
miraculous|adj.奇迹的,不可思议的
placidity|n.平静
semester|n.学期
gregarious|adj.社交的,群居的
dessert|n.餐后甜点
accept|vt.接受,认可,承担,承兑vi.同意,承认
appealability|可上诉性
hackles|长羽毛
magpie|n.鹊
shrink|v.收缩,(使)皱缩,缩短
joint|n.接缝,接合处,接合点,关节,(牛、羊等的腿)大块肉adj.共同的,联合的,连接的,合办的vt.连接,接合,使有接头vi.贴合,生节
cardinal|n.枢机主教,红衣主教adj.主要的,最重要的
naval|adj.海军的
unfaithfulness|不忠实
purple|adj.紫色的n.紫色
weird|adj.怪异的,超自然的,神秘的,不可思议的,超乎事理之外的n.<古><苏格兰>命运,预言,符咒
racy|adj.保持原味的,活泼的,适于赛跑的,<美>猥亵的
titular|adj.有名无实的,有资格的,有头衔的n.有称号(或职称)的人
apathy|n.缺乏感情或兴趣,冷漠
prophecy|n.预言,预言能力
ignominious|adj.可耻的,不光彩的,下流的
bit|n.小块,少量,片刻,马嚼子,辅币vt.上马嚼子,控制vbl.咬n.[计]位,比特
anaerobic|adj.[微]没有空气而能生活的,厌氧性的
plenteous|adj.许多的,丰饶的,充足的,丰富的
inextricable|adj.无法解脱的,逃脱不掉的,解不开的
mystic|adj.神秘的,神秘主义的n.神秘家,神秘主义的鼓吹者
affirm|v.断言,确认,肯定
representation|n.表示法,表现,陈述,请求,扮演,画像,继承,代表
respectable|adj.可敬的,有名望的,高尚的,值得尊敬的
desktop|n.[计]桌面桌上型电脑
racialism|n.种族主义,人种偏见,种族歧视
controller|n.管理员,控制器
deserts|抛弃
answer|n.答案,回答,答辩,抗辩v.回答说,答复说,符合,反响,响应
calamity|n.灾难,不幸事件
tobacconist|n.烟草商,烟店
syndrome|n.综合病症
irresolute|adj.犹豫不决的
thicket|n.灌木丛
September|n.九月(略作Sep)
immunity|n.免疫性
disparage|vt.蔑视,贬损,使失去信誉
belly|n.腹部,胃vi.涨满
hood|n.头巾,兜帽,车蓬,引擎罩v.用头巾包裹,给...加罩,覆盖
lip|n.嘴唇,唇缘
relieve|vt.减轻,解除,援救,救济,换班
nest|n.巢,窝,休息所,隐匿处,舒适的地方,(可以一个套一个的)一套器具vi.筑巢,找鸟巢vt.造巢,使套入
wholly|adv.整个,统统,全部,专门地
creamery|n.奶油厂,乳品发售店
extenuating|adj.使减轻的,情有可原的
perfunctory|adj.马马虎虎的
eject|vt.逐出,撵出,驱逐,喷射n.推断的事物
lunch|n.午餐
frequent|adj.时常发生的,频繁的
secant|adj.切的,割的,交叉的n.割线,正切
wainscot|n.壁板,装饰墙壁的材料(如瓷砖等)vt.装上壁板
unkempt|adj.蓬乱的,粗野的,不整洁的
subdivide|v.再分,细分
cognitive|adj.认知的,认识的,有感知的
abundant|adj.丰富的,充裕的,丰富,盛产,富于
solely|adv.独自地,单独地
hungry|adj.饥饿的,渴望的,荒年的,不毛的
insecure|adj.不可靠的,不安全的
since|adv.以后,后来,以前prep.自从,自...以来conj.自...以后,自...以来,因为,既然
bemused|adj.困惑的,发呆的
cadaver|n.死尸,尸体
linen|n.亚麻布,亚麻制品,亚麻纤维制成的优质纸adj.亚麻布制的,亚麻的
elaboration|n.苦心经营,苦心经营的结果,详尽的细节
magical|adj.不可思议的
opt|vi.选择
scissors|n.剪刀
subvert|vt.推翻,暗中破坏,搅乱
unfading|adj.不褪色的,不凋萎的,不衰的,可靠的,永不辜负期望的
audition|n.听,听力,试听
critique|n.批评
disdainfully|adv.轻蔑地
merry|adj.欢乐的,愉快的
mouth|n.口,嘴
grieve|v.(使)悲痛,(使)伤心,忧伤
alone|adj.单独的,独一无二的,孤独的,独自的adv.独自地
ambitious|adj.有雄心的,野心勃勃的
redeem|vt.赎回,挽回,恢复,补偿,兑换
delicacy|n.微妙
consider|vt.考虑,照顾,认为
quintessential|adj.精萃的,精髓的
unspotted|adj.清白的
inset|n.插入物,插进
engaged|adj.忙碌的,使用中的
towards|prep.向,朝,对面,接近,对,有助于
streamline|adj.流线型的
ordain|vt.注定,规定,任命(牧师)vi.颁布命令
pinch|n.捏,撮,收缩,紧急关头,匮乏,压力vt.掐,夹痛,修剪,勒索,使感缺乏,使萎缩,偷vi.收缩,节省
phrase|n.短语,习语,惯用语,成语,措词vt.用短语表达
month|n.月
louse|n.虱子,寄生虫
squeamish|adj.过于拘谨的,洁癖的,易呕吐的,神经质的
fellowship|n.伙伴关系,交情,团体,奖学金,友谊
shot|n.开枪,射击,子弹,炮弹
term|n.学期,期限,期间,条款,条件,术语
family|n.家庭,家族,家属,亲属,子女,僚属adj.家庭的,家族的
bacchanal|adj.酒神的,酒神节的,放纵的n.酒神的信徒,酒神节,狂饮作乐
idiomatically|adv.使用惯用语句,惯用地
trice|n.一刹那
Grammy|Grammy Awards 格莱美奖 ; 葛莱美奖 ; 格莱美音乐奖 ; 格莱美音乐大奖
sponsor|n.发起人,主办者,保证人,主办人vt.发起,主办v.赞助
slanderous|adj.诽谤性的
sunbath|n.日光浴太阳灯浴
mnemonic|adj.记忆的,记忆术的
docility|n.顺从,温顺
beyond|prep.在(到)...较远的一边,超过,那一边adv.在远处n.远处
submissiveness|n.柔顺,服从
blame|n.过失,责备vt.责备,谴责
spine|n.脊骨,书脊,地面隆起地带,中心,剌
egress|n.出口,外出vi.外出
revolt|v.反抗,起义,反叛,反感,厌恶
confrontational|反传统
disengaged|adj.自由的,闲散的,空闲的
forgetfully|adv.不注意地,健忘地
icicle|n.垂冰,冰柱
melted|融化
demographic|adj.人口统计学的
sporadically|adv.偶发地,零星地
neurology|n.神经学,神经病学
undrinkable|adj.不能喝的，不能饮用的
bight|n.曲线
miss|n.过错,避免,失败,小姐,姑娘vt.未得到,未达到,未听到,思念,未觉察,错过,遗漏,逃脱vi.失败,击不中
barricade|v.设路障n.路障
instigation|n,教唆,.鼓动,煽动
spurious|adj.伪造的,假造的,欺骗的
gurgle|n.(流水的)汩汩声,欢乐的(咯咯声),(人发)咯咯声,汩汩地流vi.(流水)作汩汩声
requisite|adj.需要的,必不可少的,必备的n.必需品
levy|n.征收,征税,征兵v.征收,征集,征用
murderer|n.杀人犯,凶手
embezzler|n.盗用公款者,侵占公款犯
ingress|n.进入,入口处,准许进入
rooster|n.雄禽,<主美>公鸡
buttress|n.(建筑)扶壁,支持物vt.支持,(以扶壁)扶住
choir|n.唱诗班,唱诗班的席位
reckless|adj.不计后果的
insider|n.内部的人,会员,知道内情的人,权威人士
ultimatum|n.最后通谍
susceptible|adj.易受影响的,易感动的,容许...的n.(因缺乏免疫力而)易得病的人
strew|vt.散播,点缀,撒满
scenic|adj.舞台的,布景的,景色优美的,戏剧性的n.风景照片,风景影片
contributor|n.贡献者,捐助者,投稿者
leafstalk|n.[植]叶柄
honesty|n.诚实,正直
tragic|adj.悲惨的,悲剧的n.(文艺作品或生活中的)悲剧因素,悲剧风格
metronome|n.节拍器
brainwash|n.洗脑vt.对人洗脑,以宣传说服
podiatrist|n.足病医生
proximate|adj.最近的
commit|vt.犯(错误),干(坏事),把...交托给,提交,答应负责
feast|n.节日,盛宴,筵席,宴会,酒席vt.盛宴,款待,享乐,请客vi.参加宴会,享受
hash|n.无用信息,杂乱信号,复述vt.切细,搞糟,推敲n.无用信息,杂乱信号
view|n.景色,风景,观点,见解,观察,观看,意见,认为vt.观察,观看
rack|n.架,行李架,拷问台,小步跑,烧酒,破坏vt.放在架上,在架上制作,折磨,加以拷问,使痛苦,榨取vi.在饲草架装满干草,变形,(云)随风飘,(马)小步跑
syntactic|adj.依据造句法的
chastisement|n.惩罚
Bible|n.《圣经》
tyrannically|adv.残暴地,专横地
pony|n.小型马v.付清adj.小型的,(新闻)每日摘要的
risque|adj.<法>(作品等)淫秽的,败坏风俗的
rich|adj.富的,有钱的,富有的,富饶的,肥沃的,充足的,丰富的
buggy|adj.多虫的,臭虫成灾的,<俚>神经病的n.<美>童车,<俚>尤指旧汽车,双轮单座的轻马车
efficacious|adj.有效的,灵验的
ostracize|vt.(古希腊)贝壳放逐法,放逐,排斥
underground|adj.地下的,地面下的,秘密的n.[英]地铁adv.在地下,秘密地
gustation|n.尝味,味觉
petty|adj.小的,不重要的,小规模的,小型的,细微的,小器的,卑鄙的
discouraging|adj.令人气馁的
my|pron.我的int.<口>嗳呀!啊呀![域]Malaysia,马来西亚
flowerpot|n.花盆,花钵
qualitatively|adv.质量上
snail|n.蜗牛,迟钝的人v.捉蜗牛,缓慢移动
already|adv.已经
impoverishment|n.贫穷,穷困
bumptious|adj.盲目自夸的,盲目自大的,傲慢的
sleepiness|n.想睡
percipience|n.知觉,洞察
team|n.队,组
grueling|n.重罚,严惩
attendant|n.服务员
histology|n.[生物]组织学
honed|金属表面磨损
chimera|n.[希神]狮头,羊身,蛇尾的吐火怪物,妖怪,狂想
deft|adj.敏捷熟练的,灵巧的
evade|v.规避,逃避,躲避
controller|n.管理员,控制器
attention|n.注意,关心,关注,注意力,(口令)立正!
borne|vbl.bear的过去分词
injure|vt.损害,伤害v.伤害
scientist|n.科学家
summer|n.夏季vi.避暑,过夏天adj.夏季的,在夏季的
appoint|vt.约定,指定(时间,地点),任命,委任
motel|n.汽车旅馆
create|vt.创造,创作,引起,造成
indictment|n.控告
clad|vt.在金属外覆以另一种金属adj.穿衣的vbl.clothe的过去式和过去分词
comb|n.梳子,梳,鸡冠,蜂巢vi.梳(发),搜索
rein|n.缰绳,统治,支配vt.以缰绳控制,统治,驾驭vi.勒住马,止住
pathetic|adj.可怜的,悲惨的
grogginess|不稳
trenchant|adj.锋利的
galactic|adj.极大的,银河的,乳汁的
character|n.(事物的)特性,性质,特征(的总和),(人的)品质,字符,性格,特征,人物vt.写,刻,印,使具有特征
disingenuous|adj.无诚意的
Allah|n.阿拉,真主(伊斯兰教信奉的唯一的名称)
outre|adj.越出常轨的,过度的
rejection|n.拒绝
homogeneity|n.同种,同质,同次性
skit|n.讽刺话,幽默故事,若干,一群
heartiness|n.诚实,热心
relocation|n.再布置,变换布置
succour|n.(succor)援助者,救援人员
emphatically|adv.强调地,用力地
expel|v.驱逐,开除,排出,发射
illumination|n.照明,阐明,启发,灯彩(通常用复数)
barrenness|不育症,不孕症
deferentially|adv.表示敬意地,谦恭地
firm|n.公司,(合伙)商号adj.结实的,坚硬的,坚定的,坚固的,牢固的,稳固的,严格的vt.使牢固,使坚定vi.变稳固,变坚实adv.稳固地,坚定地
ready|adj.有准备的,准备完毕的,甘心的,情愿的,现成的,迅速的
continuous|adj.连续的,持续的
bar|n.条,棒(常用作栅栏,扣栓物),横木,酒吧间,栅,障碍物vt.禁止,阻挡,妨碍,把门关住,除...之外,(Bar)律师业
fiasco|n.惨败,大失败,可耻的下场
surmountable|adj.可战胜的,可克服的
holdup|n.拦劫行人的强盗行为,劫盗,无理的讨价,停顿
sterile|adj.贫脊的,不育的,不结果的,消过毒的,毫无结果的
amidst|prep.在...当中
denote|vt.指示,表示
peek|n.一瞥,匆忙看过v.偷看
consultant|n.顾问,商议者,咨询者
stymie|n.[高尔夫]妨碍球v.从中作梗,完全妨碍
sonata|n.[音]奏鸣曲
scaremonger|n.扰乱社会民心的人,散布谣言的人
irrepressible|adj.镇压不住的,抑制不住的
racial|adj.人种的,种族的,种族间的
affordable|可承受
unwitting|adj.不知情的
claim|n.(根据权利提出)要求,要求权,主张,要求而得到的东西vt.(根据权利)要求,认领,声称,主张,需要
ruth|n.怜悯,悲哀
treatment|n.待遇,对待,处理,治疗
freshman|n.新生,大学一年级学生
calcium|n.[化]钙(元素符号Ca)
fornicate|vi.通奸adj.弓形的,拱状的
gorgeous|adj.华丽的,灿烂的
parsimony|n.过度节俭,吝啬
noteworthiness|n.值得注意,显著
stunt|v.阻碍...发育,妨碍...生长,作惊人表演,使绝招n.发育迟缓,矮小的人(或物),惊人表演,绝技
saffron|n.[植]藏红花,干藏红花粉(用于食品上色和调味的)金黄色,桔黄色adj.藏红花色的
suck|v.吸,吮,吸取
immanent|adj.内在的,固有的,[宗](上帝)无所不在的
farrow|n.一窝小猪,猪的一胎,下小猪vt.下(小猪)adj.(母牛)未怀孕的
ballyhoo|n.大肆宣传,大吹大擂,喧噪v.大肆宣传,大吹大擂
payable|adj.可付的,应付的
assignment|n.分配,委派,任务,(课外)作业
disclosure|n.揭发,败露,败露的事情
monopolise|vt.(monopolize)垄断,获得....的专卖权
hear|vt.听到,听说,听取,审理,允许vi.听见,听到
incursion|n.袭击,侵入
etymology|n.语源,语源学
impediment|n.妨碍,阻碍,障碍物,(言语)障碍,口吃,障碍物
tissue|n.薄的纱织品,薄纸,棉纸,[生]组织,连篇
tapeworm|n.[动]绦虫
rubicund|adj.(脸色,肤色等)红润的,透红的
auxin|n.茁长素,植物激素
preclude|n.排除
broken|adj.坏掉的,患病的,被制服的,断掉的vbl.break的过去分词
twin|n.双胞胎中一人,孪生子adj.双胞胎的,一对的,相似的vi.生双胞胎,成对vt.孪生,使成对
monocracy|n.独裁政治
saviour|n.[亦作savior]救星,[TheSaviour]救世主,耶稣基督
sizeable|adj.相当大的,大的
distribution|n.分配,分发,配给物,销售,法院对无遗嘱死亡者财产的分配,分布状态,区分,分类发送,发行
subtract|v.(～from)减去,减
hardy|adj.难的,艰苦的，勇敢的adv.努力地,辛苦地,坚硬地
reliant|adj.信赖的,依靠的,信赖自己的
festoon|n.花彩vt.结彩于,使成为花彩形
butter|n.黄油,牛油vt.涂黄油于...上
braiding|编织物缏饰
ambulance|n.战时流动医院,救护车
conjugal|adj.结婚的,夫妇间的
whereas|conj.然而,反之,鉴于,尽管,但是
perigee|n.[天]近地点
fine|adj.美好的,优良的,杰出的,精美的,杰出的,细,纤细,纯粹n.罚款,罚金,晴天,精细vt.罚款,精炼,澄清vi.变清,变细adv.<口>很好,妙,[常用于构成复合词]细微地,精巧地
socialistic|adj.社会主义的
subtract|v.(～from)减去,减
appurtenances|n.附属物
abbey|n.修道院,修道士（总称）
cherished|珍爱
inexhaustibly|adv.无穷尽地
apotheosis|n.尊为神,神化,颂扬,崇拜,典范
escapade|n.异常出轨的行为
cliche|n.陈词滥调,铅版adj.陈腐的
pigsty|n.猪舍,脏房子
pulley|n.滑车,滑轮
buckle|n.带扣v.扣住,变弯曲
setback|n.顿挫,挫折,退步,逆流,(疾病的)复发
commiserate|v.怜悯,同情
sequester|adv.幽静的,隐蔽的vt.使隐退,使隔绝,扣押,没收
blissful|adj.有福的
delight|n.快乐,高兴,喜悦v.(使)高兴,(使)欣喜
group|n.团体,组,团,群,批,[地]界,[化]基v.聚合,成群
imperfection|n.不完整性,非理想性
meager|n.兆
funicular|adj.索状的n.索道
precipice|n.悬崖
handiwork|n.手工,手艺,手工
plaid|n.格子花呢披肩,格子花呢
brassy|adj.象黄铜的,厚脸皮的n.铜头高尔夫球棍
grab|v.抢夺,攫取,夺取
optimism|n.乐观,乐观主义
fiber|n.fibre光纤
succinct|adj.简洁的,紧身的,压缩在小范围内的
blossom|n.花(尤指结果实者),花开的状态,兴旺期vi.开花,兴旺,发展
jungly|adj.丛林的
revolver|n.连发左轮手枪，旋转者，旋转式装置
lobby|n.大厅,休息室,<美>游说议员者vi.游说议员,经常出入休息室vt.对(议员)进行疏通
outre|adj.越出常轨的,过度的
chink|n.裂口,裂缝,叮当声v.(使)叮当响
blatantly|adv.喧闹地,看穿了地
bamboo|n.竹子
provincialism|n.地方风尚
magazine|n.杂志,期刊,军火库,弹药库,(枪、炮的)弹仓,胶卷盒
hostel|n.宿舍,旅店,客栈
goal|n.目的,目标,守门员,球门,(球赛等的)得分
enliven|vt.使生气的,使活泼,使生动
acidity|n.酸度,酸性,[医]酸过多,胃酸过多
existentialist|n.存在主义者adj.存在主义的
swam|vbl.swim的过去式
prioritization|优先顺序化
extant|adj.现存的,未毁的,<古>突出的,显著的
coaming|n.舱口栏板,边材
lactic|adj.乳的,乳汁的
society|n.社会,...会,...社,友伴,交际,社交界,上流社会
larch|n.落叶松属植物,其木材
sphere|n.球,球体,范围,领域,方面,圈子,半球
restaurant|n.餐馆,饭店
broom|n.扫帚,[植]金雀花vt.扫除
hinder|adj.后面的v.阻碍,打扰
rebellious|adj.造反的,反叛的,反抗的,难于对付的
whimsical|adj.反复无常的,古怪的
mass|n.块,大多数,质量,群众,大量adj.群众的,大规模的,集中的vt.使集合vi.聚集
replete|adj.充满的
sideboard|n.餐具柜
strap|n.带,皮带vt.用带缚住,用带捆扎
willfully|adv.任性固执地,蓄意地
banking|n.银行业
seedless|adj.无核的
respective|adj.分别的,各自的
rustiness|n.生锈,声音沙哑
canon|n.教会法教规,教规,(基督教的)正典圣经(简称正经),一个作家的真作日本佳能公司
elate|vt.使兴高采烈,使得意
misanthrope|n.厌恶人类的人,不愿与人来往者
dormancy|n.睡眠,冬眠,隐匿
drivel|vi.淌口水,说傻话vt.胡说n.流口水,胡言乱语,糊涂话
fullness|n.满,充满,丰富,成熟
truncate|v.截去(园锥等的)尖端,修剪(树等),把...截短adj.截短的,(羽,叶)平截的,平头的
topography|n.地形学
misgiving|疑惧,疑虑
visibility|n.可见度,可见性,显著,明显度,能见度
brewery|n.酿酒厂
uncanny|adj.离奇的
petitioner|n.请求者
heresy|n.异端,异教
touchy|adj.暴躁的,难以处理的,易起火的
curmudgeonly|adj.小气的,不和悦的
hypochondriacal|adj.忧郁症的,过分担心自己健康的
tolerant|adj.容忍的,宽恕的,有耐药力的
receptacle|n.容器,[植]花托,[电工]插座
dipper|n.浸渍者,汲取的人,浸染工,显影液容器,北斗七星
unpopular|adj.不流行的,不受欢迎的
entertainment|n.款待,娱乐,娱乐表演
erectness|
iguana|n.[动]鬣蜥(一种产于南美洲和西印度群岛的大蜥蜴)
dissolute|adj.放荡的,风流的,肆意挥霍的
jeopardize|v.危害
summarize|v.概述,总结,摘要而言
towel|n.手巾,毛巾v.用毛巾擦
redirection|重定向
whetstone|n.磨石,油石
water|n.水,雨水,海水,水位,水面,流体vt.喷淋,供以水,注入水,使湿vi.流泪,加水adj.水的,水上的,水生的,含水的
egocentricity|n.自我中心,自私自利
egocentricity|n.自我中心,自私自利
slapdash|adj.匆促的
maharaja|n.王公(印度对君候之敬称)
voluptuous|adj.艳丽的,奢侈逸乐的
except|vt.除,把...除外,反对,不计vi.反对prep.除了...之外,若不是,除非conj.只是,要不是
recognizance|n.[律]保证书,保证金,保释金
rainy|adj.下雨的,多雨的
sifter|n.负责筛选的人,筛子
stoic|n.高度自制者；坚忍克己之人
downward|adj.向下的
bitterness|n.苦味,辛酸,苦难
document|n.公文,文件,文档,档案,文献v.证明
horrifyingly|
monitory|adj.训诫的n.告戒书
melange|n.混合物,大杂烩,杂乱的一群,[纺]混色纱
fudge|n.梦话,胡话,纸中另版插印记事int.胡说八道!vi.蒙混,逃避责任vt.粗制滥造,捏造
storm|n.暴风雨,暴风雪v.狂怒咆哮abbr.[军]Sensor,Tank,Off-RouteMine,路外反坦克雷传感器
astrology|n.占星术,占星学(以观测天象来预卜人间事务的一种方术)
inadmissibility|n.不许可的事,难承认的事
stall|n.货摊,畜栏,厩,出售摊v.(使)停转,(使)停止,迟延
massacre|n.残杀,大屠杀v.残杀,集体屠杀
carcinogen|n.致癌物质
err|vi.犯错,做错,犯罪,[废]走上歧途
peregrinate|vi.vt.旅行
listless|adj.倦怠的,冷漠的，情绪低落的
experience|n.vt.经验,体验,经历,阅历
sobriquet|n.假名,绰号
venue|n.犯罪地点,审判地,集合地点,会议地点,比赛地点,管辖地
condense|v.(使)浓缩,精简
internecine|adj.互相残杀的,两败俱伤的,内部冲突的
ammonia|n.[化]氨,氨水
limb|n.肢,翼,分支
eroded|腐蚀
gloss|n.光泽的表面,光彩,欺人的表面,假象,注释vt.使有光彩,掩饰,上光于,注释,曲解vi.发光,作注释
disentangled|解开
subtraction|n.减少
huffy|adj.发怒的
rep|n.棱纹平布
operation|n.运转,操作,实施,作用,业务,工作,手术,军事行动
already|adv.已经
smithereens|n.碎片,碎屑
influential|adj.有影响的,有势力的
twiddle|vt.捻起来,抚弄,玩弄,旋弄vi.玩弄n.捻
vivacious|adj.活泼的,快活的,[植]多年生的
dental|adj.牙齿的
monotheistic|adj.一神论的
session|n.会议,开庭
Europe|n.欧洲
archivist|n.案卷保管人
futile|adj.琐细的,无用的,无效果的,(人)没有出息的
leisure|n.空闲,闲暇,悠闲,安逸
splutter|n.杂乱而仓促的话,杂乱的声音
theistic|adj.有神论的
fin|n.鳍,鱼翅,鳍状物,五元纸币vi.猛挥鳍,露鳍于水面的vt.装上翅,切除鳍
integrating|结合
impregnate|vt.使怀孕,使受精,使充满,注入,灌输adj.怀孕的,充满的
appertain|v.属于
preamble|n.导言
limitless|adj.无限的,无界限的
authentic|adj.可信的
brunch|n.早午餐
cloudburst|n.倾盆大雨,豪雨
choreography|n.舞蹈术,舞台舞蹈
belonging|[常用复]附属品,附件属性
demonstrate|vt.示范,证明,论证vi.示威
creditably|adv.有名誉地,不愧,美满地
pointless|adj.无意义的
ornamental|n.装饰物,观赏植物adj.装饰性的,装饰的,装饰用的
wistful|adj.渴望的,想望的
foppery|n.纨绔习气
dyke|n.vt.(dike)沟,渠,堤坝,<美俚>(女子)搞同性关系n.<俚>(尤指男性化的)女子同性恋者
err|vi.犯错,做错,犯罪,[废]走上歧途
pawnbroker|n.典当商
southwest|n.西南方adj.西南的,向西南方的
beget|vt.(书面语)招致,产生,引起
terrapin|n.[动]龟鳖类
incompetence|n.无能力,不适当[律]无行为能力,法律上无资格
italic|adj.[印]斜体的n.<总称>印欧语系,意大利语族,斜体字,斜体
asceticism|n.禁欲主义,苦行
viscid|adj.粘的,胶粘的,粘质的,半流体的
dynamo|n.发电机
irrepressible|adj.镇压不住的,抑制不住的
swirling|旋涡涡流
plagiarist|n.剽窃者,文抄公
infallible|adj.没有错误的,确实可靠的n.一贯正确的人
submissive|adj.顺从的
normally|adv.正常地,通常地
farming|n.耕作,农业,农事,畜牧
elusion|n.逃避,规避
assess|vt.估定,评定
downtrodden|adj.被践踏的,被蹂躏的,被压制的
gusty|adj.阵风的,多阵风的,起大风的,迸发的
perspective|n.透视画法,透视图,远景,前途,观点,看法,观点,观察
shady|adj.成荫的,多荫的,阴暗的
decameter|n.<美>(decametre)十米
impassivity|n.平静,无神经,泰然自若
lifelike|adj.逼真的
voyeuristic|adj.喜好窥阴的
spatter|v.溅污n.滴落
daunting|adj.使人畏缩的
skim|v.撇去
strategic|adj.战略的,战略上的
epicure|n.美食家,老饕,<古>享乐主义者
overrule|vt.驳回,否决,支配,制服
path|n.小路,小径,路线,轨道,通道
closet|n.壁橱,储藏室,厕所adj.关起门来的vt.关入私室密谈
scepter|n.笏,节杖,王权vt.授予节杖,拥登王位,授与王权
dispensary|n.(学校、兵营或工厂的)诊疗所,药房,防治站
frustration|n.挫败,挫折,受挫
explicitly|adv.明白地,明确地
beleaguer|vt.围,围攻
photorespiration|n.[生化]光呼吸(作用)
repulsive|adj.推斥的,排斥的,严拒的,令人厌恶的
confidentiality|n.机密性
crunch|v.嘎扎嘎扎的咬嚼,压碎,扎扎地踏过n.咬碎,咬碎声,扎扎地踏
climacteric|n.转变期,[医]更年期,绝经期,[植]呼吸峰
bear|n.熊v.负担,忍受,带给,具有,挤,向
placate|v.安抚
visage|n.<书>面貌,容貌
serially|adv.连续地,连续刊载地
Fahrenheit|adj.华氏温度计的n.华氏温度计,华氏温度计
dainty|n.适口的食物,美味adj.秀丽的,优美的,讲究的,挑剔的,适口的
video|n.电视,录象,视频
renew|vt.使更新,使恢复,重申,补充,续借,复兴vi.更新,重新开始
boom|n.繁荣,隆隆声v.发隆隆声,兴隆,大事宣传
breaker|n.断路器
airily|adv.轻盈地,快活地
convoy|n.护送,护卫vt.护航,护送
wily|adj.老谋深算的
apprise|vt.通知
caribou|n.北美产驯鹿(Rangifer)
demonstrative|adj.说明的,(语法)指示的
cetacean|adj.鲸类的,鲸的n.鲸类动物,鲸
instant|adj.立即的,直接的,紧迫的,刻不容缓的,(食品)速溶的,方便的,即时的
exaction|n.勒索,苛求
misdirect|vt.误导,写错地址
hangover|n.残留,遗物,宿醉
flighty|adj.忽发奇想的,反复无常的,轻浮的,轻狂的,心情浮动的
promenade|n.散步v.散步adj.散步的
maritime|adj.海上的,海事的,海运的,海员的
prefix|n.[语]前缀,(人名前的)称谓(如Mr.Dr.Sir等)
apprehended|理解
singer|n.歌手
fashionably|adv.时髦地,按照流行地
tariff|n.关税,关税表,税则,(旅馆,饭店等的)价目表、价格表vt.课以关税
roundup|n.赶拢一块的牲畜,围捕,驱集,摘要
veneer|n.薄板,单板,胶合板,饰面,外表,虚饰vt.镶饰,胶合,虚饰
pithy|adj.有髓的,精练的
felon|n.重罪人,蛇头,瘭疽adj.<古>凶恶的,邪恶的,残忍的
Scandinavian|n.(北欧一地区,包括挪威、瑞典、丹麦、冰岛的)斯堪的纳维亚人[语
housebound|adj.居家不外出的,不能离家的
twist|n.一扭,扭曲,盘旋,曲折,歪曲,手法,螺旋状vt.拧,扭曲,绞,搓,捻,使苦恼,使转动,编织vi.扭弯,扭曲,缠绕,扭动,呈螺旋形
blow|n.殴打,突然的打击v.风吹,吹气于,叫,喘气
vapid|adj.索然乏味的
circumspectly|adv.慎重地,留心地
indefinitely|adv.不确定地
layoff|n.临时解雇,操作停止,活动停止期间,失业期
qualm|n.疑虑
least|adj.最小的,最少的adv.最少,最小
inaudibility|n.听不见,不可闻
bureaucrat|n.官僚主义者
runway|n.飞机跑道,斜坡跑道,河道
replace|vt.取代,替换,代替,把...放回原处
strut|n.高视阔步,支柱,压杆vi.大摇大摆地走,肿胀vt.支撑,炫耀
swivel|v.旋转
proximity|n.接近,亲近
ascendancy|n.优势,支配(或统治)地位
feeling|n.触觉,知觉,感觉,情绪,同情adj.富于感情的,富于同情心的,衷心的,有同情心的,有感觉的,仁慈的
natural|adj.自然的,自然界的,关于自然界的,天生的,天赋的,普通的,正常的,简单自然的本位号
exposure|n.暴露,揭露,暴光,揭发,揭露,位向,方向,陈列
expurgate|v.删除
interim|adj.中间的,临时的,间歇的n.中间时期,过渡时期,暂定
unabated|adj.不衰退的,不减弱的
nipper|n.<主英口>少年,镊子,<俚>手铐
stoppage|n.中断,填塞
gifted|adj.有天才的
purge|n.净化,清除,泻药v.(使)净化,清除,肃清,(使)通便
flak|n.高射炮火
shear|v.剪,修剪,剪切
muskie|n.<口>maskinonge
liberia|n. 利比里亚（西非国家）
indentation|n.缩排,呈锯齿状,缺口,印凹痕
divergent|adj.分歧的
ruminative|adj.默想的,沉思的
warily|adv.留心地,小心地,警惕地
submerse|v.使沉入水中,淹没
arson|n.纵火,纵火罪
arrhythmic|adj.无节奏的
self-analysis|n.自我心理分析
contraposition|n.对置,对位,对照
overpowering|adj.无法抵抗的,压倒性的
politburo|n.-ros（共产党的）政治局
foyer|n.休息室,大厅
statistically|adv.统计上地,统计地
indistinguishable|adj.不能辨别的,不能区别的
campus|n.<美>校园,大学教育
impassiveness|
direct|adj.径直的,直接的,直系的,直率的,[天]由西向东运行的,顺行的adv.直接地vt.指引,指示,指挥,命令,导演vi.指导,指挥
torrential|adj.奔流的
monk|n.修道士,僧侣
relief|n.(痛苦等的)减轻,(债务等的)免除,救济,调剂,安慰,浮雕,地貌
guardian|n.护卫者,保护人,监护人adj.守护的
tumbler|n.打滚的人,翻筋斗者,杂技演员,(平底)大玻璃杯,一杯量
self-taught|adj.自学而成的,自修的
linger|v.逗留,闲荡,拖延,游移
unfamiliar|adj.新奇的,不熟悉的,没有经验的
silent|adj.寂静的,沉默的,无声的,无记载的
sodden|adj.浸透的
aversion|n.厌恶,讨厌的事和人
attraction|n.吸引,吸引力,吸引人的事物
prime|n.最初,青春,精华adj.主要的,最初的,有青春活力的,最好的,第一流的,根本的,[数]素数的v.预先准备好,<口>让人吃(喝)足,灌注,填装
ant|n.蚂蚁
lissom|adj.柔软的（人体）
repossess|vt.收回,复得
warmth|n.暖和,温暖,热心,热情
interlocutor|n.对话者,对谈者
heirloom|n.传家宝,相传动产
subtraction|n.减少
imminence|n.迫切,急迫,迫近的危险(或祸患)
cushion|n.垫子,软垫,衬垫v.加衬垫
plenitude|n.充分
photolithography|n.影印石版术,照相平版
altered|改变
impartial|adj.公平的,不偏不倚的
additive|adj.附加的,加成的,添加的n.添加剂adj.添加的,附加的,加法的
prissy|adj.谨小慎微的
defender|n.防卫者,拥护者,辩护者,[运动]卫冕者
wholesome|adj.卫生的,有益的,健康的,有益健康的
dinginess|n.暗淡,肮脏
fiscal|adj.财政的,国库的,会计的,国库岁入的n.(苏格兰和欧洲某些国家的)检查官,印花税票
reign|vi.统治,支配,盛行,占优势n.统治,统治时期,支配
urgency|n.紧急,紧急的事,强求,催促,坚持
unnecessary|adj.不必要的,多余的
pointer|n.指示器
apposite|adj.适当的
tilt|v.(使)倾斜,(使)翘起,以言词或文字抨击
bonnily|adv.美丽地,快活地
plebiscite|n.平民制定法,公民投票
parley|n.会谈
cabin|n.小屋,船舱
congruity|n.一致,适合,调和
craziness|n.发狂,热中,狂热
acquaint|vt.使熟知,通知
yield|v.出产,生长,生产vi.(～to)屈服,屈从n.产量,收益
meditation|n.沉思,冥想
doyen|n.老资格,老前辈,首席
trustee|n.托管人,保管人,理事
entrap|v.诱陷
deceive|v.欺骗,行骗
volcano|n.火山
throb|n.悸动,脉搏vi.悸动,抽动,颤动,跳动着作痛,充满活力
frowzy|adj.不整洁的,憋闷的,有臭味的
superimpose|v.添加,双重
decide|v.决定,判决
hullabaloo|n.喧嚣,喧哗,吵闹（声）,（混乱,骚动）声
impersonal|adj.非个人的
tanker|n.油轮
alternative|n.二中择一,可供选择的办法,事物adj.选择性的,二中择一的
mustache|n.髭,胡子
chemistry|n.化学
microchip|[计]微芯片
panache|n.羽饰,华丽
messy|adj.肮脏的,凌乱的,杂乱
parental|adj.父母亲的,做双亲的
enumeration|n.列举
resilient|adj.弹回的,有回弹力的
flirt|vt.忽然弹出,挥动vi.调情,摇晃的移动,玩弄,摇晃地摆动,摆动,轻率地对待n.卖弄风情的人,调情的人
rehouse|v.移往新居,供以新住宅
satin|n.缎子,假缎,缎纹adj.绸缎做的,缎子一般的,光滑(似缎)的
February|n.二月(略作Feb)
pigment|n.[生]色素,颜料
anchorman|n.(接力赛中)末棒运动员,(汇编各地采访人员的资料并进行综合评价的)新闻节目主持人
valour|n.英勇,勇猛
fruit|n.水果,果实,果类,成果vi.结果实
cathode|n.阴极
gyrate|vi.旋转,不停地转动adj.旋涡状的
formulaic|adj.(根据)公式的,用俗套话堆砌成的,刻板的
leopardess|n.雌豹
strove|vbl.strive的过去式
discrete|adj.不连续的,离散的
decentralize|n.分散
naysayer|反对者,否认者老爱唱反调的人
cleanly|adj.喜清洁的,干净的,洁净的adv.干净地,清洁地,清白地
rattlesnake|n.<美>[动]响尾蛇
stringency|n.严格,紧迫,说服力
fatherland|n.祖国
strangulation|n.勒杀,压缩,箝制
nigh|adj.在附近的adv.在附近地prep.近于
globe|n.球体,地球仪,地球,世界
Scottish|adj.苏格兰的,苏格兰人的
instrument|n.工具,手段,器械,器具,手段
parrot|n.鹦鹉,学舌者,机械模仿别人的人vt.学舌
apologist|n.辩护者,辩证者,护教论者
prepossession|n.偏爱,先入观念
uxorious|adj.疼爱妻子的,怕老婆的
nickname|n.诨号,绰号,昵称vt.给...取绰号,给...起浑名
odium|n.憎恶,讨厌
diver|n.潜水者
main|n.主要部分,体力,力量,大陆,要点,干线adj.主要的,重要的,全力的n.[计]主群组
alkaline|adj.[化]碱的,碱性的
illuminate|vt.照明,照亮,阐明,说明,使灿烂,以灯火装饰(街道等)vi.照亮
eminent|adj.显赫的,杰出的,有名的,优良的
human|n.人,人类adj.人的,人类的,人性的,有同情心的
verbalize|v.描述
ambidextrous|adj.怀有二心的,非常灵巧的
piratical|adj.剽窃的,海盗的,盗版的
intensively|adv.强烈地,集中地
threw|vbl.throw的过去式
primp|v.打扮,装饰
genocide|n.有计划的灭种和屠杀
grave|n.墓穴,坟墓adj.严重的,(颜色)黯淡的,(声音)低沉的v.雕刻,铭记
cleverly|adv.聪明地,灵明地
knit|v.编织,密接,结合
epitome|n.摘要
factory|n.工厂,制造厂,商住花园外的代理
trough|n.槽,水槽,饲料槽,木钵
conservative|adj.保守的,守旧的n.保守派
crestfallen|adj.垂头丧气的
achievement|n.成就,功绩
deny|v.否认,拒绝
inveigh|vi.猛烈抨击,痛骂,漫骂
polarity|n.极性
confirmed|adj.证实的,惯常的,慢性的
donator|n.捐赠者
dramatic|adj.戏剧性的,生动的
cabbalah|
epidemic|adj.流行的,传染的,流行性n.时疫,疫疾流行,(风尚等的)流行,流行病
delectably|
graphics|n.(作单数用)制图法,制图学,图表算法,图形
aspirant|n.有抱负者,有野心者adj.上进的,有野心的
patronage|n.保护人的身份,保护,赞助,光顾
superman|n.具有超人能力的人,超人
investigate|v.调查,研究
horizontal|adj.地平线的,水平的
inviting|adj.引人动心的,有魅力的
rustily|adv.锈蚀地,声音沙哑地
repast|n.餐vi.设宴,就餐
preexist|v.先前存在
roadside|n.路旁adj.路旁的
blade|n.刀刃,刀片
digest|n.分类,摘要vi.消化vt.消化,融会贯通
pronounced|adj.讲出来的,显著的,断然的,明确的
inefficiently|adv.无效率地
analysis|n.分析,分解
incompressible|adj.不能压缩的
assembly|n.集合,装配,集会,集结,汇编
nerve|n.神经,胆量,勇气,叶脉vt.鼓起勇气
prehension|n.抓住,理解
curio|n.古董,古玩
favourable|adj.赞成的,称许的,有利的,顺利的n.有利
ensign|n.旗,军舰旗,军旗,徽章,<美>海军少尉
show|n.表示,展览,炫耀,外观,假装v.出示,指示,引导,说明,显示,展出,放映
stretcher|n.担架,延伸器
befuddle|vt.使酒醉昏迷,使迷惑,使迷糊
piquant|adj.开胃的,辛辣的,泼辣的,兴奋的,顽皮的,淘气的
roulette|n.轮盘赌,点线机,转迹线,刻骑缝孔的齿轮
clan|n.部落,氏族,宗族,党派
website|网站
bribery|n.行贿,受贿,贿赂
accept|vt.接受,认可,承担,承兑vi.同意,承认
titular|adj.有名无实的,有资格的,有头衔的n.有称号(或职称)的人
bacchanalia|
cyclical|轮转的,循环的
pencel|[古]小燕尾旗小三角旗狭旗
mutter|n.咕哝,嘀咕v.咕哝,嘀咕
fecund|adj.生殖力旺盛的,多产的,丰饶的,肥沃的
sensuous|adj.感觉上的,给人美感的
rubbery|adj.橡胶似的,有弹力的
such|adj.这样的,这种,某一pron.这样的人(们)或物
incipient|adj.初始的
forborne|v.forbear的过去分词
temporization|n.因循,妥协
blast|n.一阵(风),一股(气流),爆炸,冲击波vt.爆炸,,毁灭,使枯萎,损害
mainland|n.大陆
grateful|adj.感激的,感谢的
evergreen|adj.常绿的n.常绿树,常绿植物
blew|vbl.blow的过去式和过去分词
assertive|adj.断定的,过分自信的
staunch|adj.坚定的
display|vt.陈列,展览,显示n.陈列,展览,显示显示,显示器
put|vt.放,摆,安置,表达,迫使,移动,提出,赋予vi.出发,航行,发芽,击n.掷,投击,笨蛋,怪人vbl.put的过去式和过去分词adj.固定不动的
ammunition|n.军火,弹药
competitive|adj.竞争的
standing|adj.直立的,停滞的,固定的,常备的,标准的,常设的n.站立,身分,名望,持续v.站
bibliographical|adj.书籍解题的,著书目录的
middleman|n.中间人
headroom|n.[建]净空,头上空间,净空高度（拱梁等下面）
inconvenient|adj.不便的,有困难的
ungrudging|adj.慷慨的,情愿的
prelate|n.高级教士
hornless|adj.(动物等)无角的,无号角的
irreparably|adv.不能挽回地,不能恢复地
grovel|vi.趴,匍匐,卑躬屈膝,五体投地的
ponderable|adj.可以估计的
impracticable|adj.不可行的
collected|adj.收集成的,冷静的,镇定的
metronome|n.节拍器
undeceive|vt.使不受欺骗,使醒悟
standpoint|n.立场,观点
consider|vt.考虑,照顾,认为
glowing|adj.炽热的,容光焕发的,生气勃勃的
ensure|vt.保证,担保,使安全,保证得到v.确保,确保,保证
recoup|vt.赔偿,补偿,扣除vi.补偿损失
boldness|n.大胆,冒失,勇敢
flaunt|n.招展,招摇,炫耀,飘扬v.挥动,夸耀,炫耀,飘扬
larval|adj.幼虫的,幼虫状态的
maculated|弄脏
bloom|n.花,旺盛,青春v.(使)开花,(使)繁盛
sitcom|situationcomedy连续剧
bovine|adj.迟钝的,牛的,似牛的,耐心的
publication|n.出版物,出版,发行,公布,发表
impetuous|adj.冲动的,猛烈的,激烈的
habitat|n.(动植物的)生活环境,产地、栖息地,居留地,自生地,聚集处
self-indulgent|adj.放纵的,任性的
heal|v.治愈,医治,结束
executioner|n.死刑执行人,刽子手
bounce|v.(使)反跳,弹起,(指支票)被银行退票,弹跳n.(球)跳起,弹回
hormone|n.荷尔蒙,激素
tuberculosis|n.肺结核
lawgiver|n.立法者
abject|adj.卑鄙的,可怜的
prodigious|adj.巨大的
unarticulated|
practicality|n.实用性
ascertainment|n.探查,发现
mortal|n.凡人,人类adj.必死的,致命的,人类的,临终的adj.<口>极端的,非常大(长)的
cowhand|n.<美>(牧场的)牧牛工
disinter|v.掘出
circuit|n.电路,一圈,周游,巡回
dormant|adj.睡眠状态的,静止的,隐匿的
refute|vt.驳倒,反驳
perfunctoriness|
gum|n.齿龈,树脂,橡胶,橡胶树,口香糖,香口胶,泡泡糖
providentially|照天意,靠天佑
boot|n.<美>(长统)靴,靴子v.导入
knead|vt.揉(面等)成团,捏制(面包、陶器等),按摩,捏制
prowler|n.徘徊者,小偷
elder|n.年长者,老人,父辈adj.年长的,资格老的
exhilarating|adj.令人喜欢的,爽快的,使人愉快的
travail|n.辛苦
temptation|n.诱惑,诱惑物
tin|n.[化]锡,马口铁,罐vt.涂锡于adj.锡制的
alertness|n.警戒,机敏
deferrable|adj.可延期的,可暂缓的,可缓征的
hasty|adj.匆忙的,草率的
admissibility|n.可容许,有入场的资格
mistaken|adj.犯错的,错误的
inured|生效
resistance|n.反抗,抵抗,抵抗力,阻力,电阻,阻抗
instrumentation|n.使用仪器
wit|n.智力,才智,智慧
snack|n.小吃,快餐,一份v.吃快餐(小吃)
transitoriness|n.暂时,短暂
atheism|n.无神论
excite|vt.刺激,使兴奋,使激动vi.<口>兴奋,激动
hypnosis|n.催眠状态,催眠
gag|n.塞口物,随口科白,打诨,箝口物,箝制言论,讨论终结vt.塞物于...的口中,禁止,使窒息,使呕吐,压制言论自由,插科打诨,欺骗vi.窒息,作呕,欺骗,插科打诨
enliven|vt.使生气的,使活泼,使生动
clanger|n.大失策,过失
retreat|vi.撤退,退却n.撤退,退却
airlift|n.(尤指紧急情况下或陆上交通断绝时的)空运,空运物资vt.空运
constringe|vt.使收缩,使收敛,压缩
prance|n.(马)后足立地腾跃,昂首阔步vi.腾跃,欢跃,昂首阔步vt.使腾跃
latitude|n.纬度,范围,(用复数)地区,行动或言论的自由(范围)
heartland|n.心脏地区,中心地带
intangible|adj.难以明了的,无形的
demonstrative|adj.说明的,(语法)指示的
compactly|adv.细密地,简洁地
irony|n.反话,讽刺,讽刺之事
exhilarating|adj.令人喜欢的,爽快的,使人愉快的
multifarious|adj.种种的,各式各样的
headquarter|v.以...作总部,设总公司于...
atomic|adj.原子的,原子能的,微粒子的
chalet|n.瑞士山中的牧人小屋
beetle|n.甲虫vi.悬垂,突出
cushion|n.垫子,软垫,衬垫v.加衬垫
wedding|n.婚礼,婚宴,结合,结婚典礼
committed|adj.效忠的；忠于…的
violation|n.违反,违背,妨碍,侵害,[体]违例,强奸
protuberant|adj.突起的,凸出的,隆起的
couch|n.(文学)床,睡椅v.(用语言)表达
fold|n.折,羊栏,折痕,信徒vt.折叠,包,合拢,抱住,笼罩,调入,交迭vi.折叠起来,彻底失败
purposively|
harmful|adj.有害的,伤害的
redoubtable|adj.可怕的
customs|n.进口税,海关
grapple|v.格斗
constructive|adj.建设性的
promulgation|n.颁布
bawdily|adv.淫秽地
theatre|n.剧场,戏院,电影院,阶梯教室,手术教室,手术室,全体观众,戏剧
indoctrinate|v.灌输
cartoonist|n.漫画家
beseech|v.恳求,哀求
cafeteria|n.自助餐厅
sunshine|n.阳光
spirited|adj.英勇的
jerk|n.性情古怪的人,急推,猛拉,肌肉抽搐,(生理)反射,牛肉干vi.痉挛,急拉,颠簸地行进vt.猛拉
rind|n.外壳
cake|n.蛋糕,饼,块
slightly|adv.些微地,苗条地
among|prep.在...之中,...之一
interactive|adj.交互式的
limb|n.肢,翼,分支
tact|n.机智,手法,老练,角觉vt.对（刺激）操作性应答vi.(以言语或声音)操作性应答
stream|n.溪,川,流,一股,一串,河流v.流,涌,流注
barman|n.酒吧间招待员
lot|n.签,抽签,一堆,许多,命运,一块地,份额vt.划分vi.抽签,抓阄
genera|类,属
intermittently|adv.间歇地
catcall|n.不满之声,嘘声v.发嘘声
ton|n.吨,大量,许多
ceil|vt.装天花板,装船内格子板
possession|n.拥有,占有,所有,着迷,领土,领地,财产(常用复数),自制
emigrant|n.移居外国者,移民
smoking|n.抽烟,冒烟
overshadow|v.遮蔽,使...失色
haziness|n.朦胧之性质或状态
facial|adj.面部的
impure|adj.不纯的
housebreaker|n.侵入家宅者,拆屋者,强盗n.侵入家宅者,强盗,<英>拆旧屋者
induce|vt.劝诱,促使,导致,引起,感应
engender|v.造成
incarcerate|vt.把...关进监狱,监禁,幽闭
moisturize|vi.变潮湿,增加水分vt.使增加水分
craftsman|n.工匠,手艺精巧的人,艺术家
acupuncture|n.针刺疗法v.施行针刺疗法
fumigate|vt.熏制,使发香
transferee|n.[律](财产,权利等)受让人,承让人,被调任者
comply|vi.顺从,答应,遵守
compassion|n.同情,怜悯
lurid|adj.<罕>苍白的,可怕的,血红的,耸人听闻的
have|vt.有,持有,拿,从事(某事)aux.已经
receptor|n.接受器,感受器,受体
freshwater|n.淡水(不是海洋水的),湖水,内河
December|n.十二月(略作Dec)
planar|adj.平面的,平坦的
freehand|adj.凭手画的n.徒手画n.adj.徒手画(的)
diligently|adv.勤勉地,坚持不懈地
scalar|adj.梯状的,分等级的,数量的,标量的n.数量,标量
shabby|adj.破旧的,褴褛的,低劣的,卑鄙的,不公平的
idiotic|adj. 白痴的；愚蠢的
sweeten|v.(使)变甜,加糖
sovereign|n.君主,统治adj.至高无上的,君主的,独立自主的,完全的
arcade|n.[建]拱廊,有拱廊的街道
explanation|n.解释,解说,说明,辩解,互相讲明
sniffle|vi.鼻子哼哼的做声,抽鼻涕n.抽鼻子
manipulate|vt.(熟练地)操作,使用(机器等),操纵(人或市价、市场),利用,应付,假造vt.(熟练地)操作,巧妙地处理
apocalyptically|
intrepidness|
perpetuation|n.永存,不朽
antics|n.滑稽的动作,古怪的姿态
grudge|v.不给予
anyhow|adv.无论如何,总之
declension|n.[文法]词尾变化,格变化,倾斜,衰退
unutterably|adv.非言语所能表达地
unyielding|adj.坚硬的,不能弯曲的,不屈的
laundry|n.洗衣店,要洗的衣服,洗熨
toad|n.[动]蟾蜍,癞蛤蟆,讨厌的家伙
smuggle|n.走私,偷带v.走私
avail|vi.有益于,有帮助,有用,有利vt.有利于n.效用,利益
physical|adj.身体的,物质的,自然的,物理的n.体格检查
butler|n.仆役长,男管家
wildness|n.野生,野蛮
lick|n.舔,少许,打vt.舔,卷过,鞭打,克服,征服vi.轻轻拍打
navigation|n.航海,航空,导航,领航,航行
energy|n.精力,精神,活力,[物]能量
dissimilarly|adv.不同地
largely|adv.主要地,大量地,很大程度上
vindictive|adj.报复性的
disgorge|v.吐出
verbiage|n.空话
introverted|adj.内向的,含蓄的,闭关自守的
woodpile|n.木料堆
buck|n.<美口>元,雄鹿,公羊,公兔v.(马等)突然一跃(将骑手摔下)
aggravate|vt.使恶化,加重
ascend|v.攀登,上升
jugglery|n.戏法,杂耍,魔术
doll|n.洋娃娃,玩偶,美丽但无头脑的女子,<俚>美男子
bole|n.树干,树身
buff|n.浅黄色,软皮
arraign|vt.提问,传讯,责难
trapezium|n.[数]不等边四边形,梯形
pathologic|adj.病理的,病态的
legless|adj.无腿的
treachery|n.背叛,背信弃义,变节,叛逆行为
treasury|n.财政部,国库
foliage|n.树叶,植物
liter|n.公升
intellect|n.智力
ecologically|生态
hurling|n.爱尔兰式曲棍球
guilt|n.罪行,内疚
ohm|n.[物]欧姆
conduce|v.导致,有利于
brochure|n.小册子
orifice|n.孔,口
feel|vt.摸,触,试探,感觉,觉得,触摸,以为vi.有知觉,(人)有某种感觉,摸索,同情n.感觉,觉得,触摸
blunderer|n.轻率粗心的人
dripping|n.滴,滴下,滴下物,油滴
generalise|v.<主英>generalize
dodderer|
volatility|n.挥发性
wind|n.风v.绕,缠,上发条,旋紧
mastermind|v.策划
impostor|n.冒名顶替者
educationally|adv.教育地有关教育地,教育上地
they|pron.他们,它们
frenetically|
rapture|n.全神贯注,兴高采烈,欢天喜地vt.使狂喜
batter|n.击球手v.打坏,猛击
larva|n.幼虫
station|n.位置,岗位,地位,身份,...局,...站vt.驻扎,配置
variability|n.可变性
lumberjack|n.伐木工人,木材商的佣工,短茄克衫
grace|n.优美,雅致,优雅
understandable|adj.可以理解的,可懂的
future|n.未来,将来,前途,远景adj.未来的,将来的
forgo|vt.作罢,放弃
brevity|n.(时间)短暂,(讲话,文章等)简短
alcohol|n.酒精,酒
farfetched|adj.牵强的
liken|vt.把...比作
disapprove|v.不赞成
accustom|vt.使习惯于
dependency|n.依靠,信赖,从属,从属物,属国,属地
weak|adj.不牢固的,弱的,虚弱的,软弱的,淡的,疲软的,无力的,不耐用的
renovated|革新
centiliter|n.厘升
oatmeal|n.(燕)麦片,(燕)麦粥
cruelty|n.残忍,残酷
boastfully|好夸口
choreographer|n.舞蹈指导
galleon|n.大型帆船
handlebar|n.手把,八字胡
teetotalism|n.绝对禁酒
beguiling|adj.欺骗的,消遣的
armor|n.装甲
penetrable|adj.可穿透的
diphthong|n.双重元音,双元音字,连元音字
entertaining|adj.愉快的,有趣的n.招待,款待
thesis|n.论题,论文
local|adj.地方的,当地的,局部的,乡土的n.当地居民,本地新闻,慢车,局部
paddy|n.稻,谷,<俚>爱尔兰人,警察,<英口>狂怒,大怒
prattle|vi.说孩子气的话,说半截话,闲聊,胡说,唠叨vt.天真地说n.孩子话,无聊话,胡说,废话
antitoxin|n.抗毒素
studied|adj.有计划的,故意的
kindred|n.家族,相似,亲属关系,(用作复数)亲戚、族人adj.同族的,同类的,血缘的,类似的
nepotism|n.偏袒,起用亲戚,裙带关系
aim|n.目标,目的,瞄准v.对...瞄准,打算
ballet|n.芭蕾舞,芭蕾舞剧,芭蕾舞乐曲
treble|adj.三倍的,三重的,三层的,最高音部的v.成三倍,使增加两倍,增为三倍
distrain|v.[律](为抵债而)扣押(财物)
auxiliary|adj.辅助的,补助的
dawdler|n.游手好闲的人,懒人
complaisant|adj.彬彬有礼的,殷勤的,柔顺的
chronological|adj.按年代顺序排列的
war|n.战争vi.作战,打仗
flamboyant|adj.辉耀的,华丽的,火焰似的,艳丽的
dryness|n.干,干燥
topsoil|n.上层土,表层土
configuration|n.构造,结构,配置,外形
congratulatory|adj.庆祝的,祝贺的
regal|adj.帝王的,适于帝王的
dreary|adj.沉闷的
escapism|n.逃避现实,空想
augury|n.占兆,占卜,预言
oar|n.桨,橹
discourse|n.演讲,论述,论文,讲道,谈话,谈论vi.谈论,演说
adroit|adj.熟练的,机捷的
proscenium|n.(古希腊,古罗马的)舞台,舞台前部装置(包括幕布,拱形墙等)
viscosity|n.粘质,粘性
emaciation|n.瘦弱,衰弱,憔悴
inequity|n.不公平,不公正
on|prep.在...之上,依附于,临近,靠近,向,在...时候,关于,涉及adv.在上,向前,行动中,作用中
herring|n.青鱼,鲱
derrick|n.起重机,(钻井)井口上的铁架塔
pertinent|adj.有关的,相干的,中肯的
accentuation|n.重读,强调
dagger|n.短剑,匕首vt.用剑(或匕首)刺
frizz|n.卷发,卷毛,吱吱响声vt.使卷缩,使卷曲vi.卷曲,炸得吱吱响
artillery|n.炮的总称,炮兵的总称
misappropriate|v.盗用
ethnologist|n.民族学者,人种学者
exploration|n.探险,踏勘,探测,[医](伤处等的)探查,探察术
nut|n.坚果,螺母,螺帽,难解的问题
betray|vt.出卖,背叛,泄露(秘密),露出...迹象
profane|adj.亵渎的v.亵渎
feebly|adv.柔弱地,微弱地,无力地
immanent|adj.内在的,固有的,[宗](上帝)无所不在的
genre|n.类型,流派
thread|n.线,细丝,线索,思路,螺纹
inset|n.插入物,插进
elliptic|adj.椭圆形的
enlightenment|n.启迪,教化
impenitent|adj.不悔悟的,顽固的n.不悔悟的人,顽固的人
allege|vt.宣称,断言
unskillfulness|
phenomenology|n.现象学
viscera|n.内脏,内容
prowess|n.威力
fantasia|n.幻想曲
glacier|n.冰河
colonization|n.殖民地化,殖民
separability|n.可分离性
minaret|n.尖塔
jocundity|n.欢乐
scuba|n.水中呼吸器
vocally|adv.用声音,用口头
turncoat|n.背叛者,变节者
inferred|推断
legerdemain|n.戏法,骗术,诡辩,巧妙的花招
snack|n.小吃,快餐,一份v.吃快餐(小吃)
odium|n.憎恶,讨厌
sedentary|adj.久坐的,坐惯的,土生的,不移栖的,沉积的n.惯于久坐的人
paddock|n.(马厩或宅房的)小牧场,围场
immunization|n.使免除,使免疫
crib|n.婴儿床,食槽,栅栏vi.抄袭vt.拘禁,关入栅栏
siren|n.汽笛,警报器,空袭警报,妖妇v.(救火车等)响着警报器行驶
earshot|n.听力所及之范围
disobey|v.违反,不服从
polarity|n.极性
liquidity|n.流动性,流畅
necessitous|adj.贫困的
nitinol|
whimsicality|n.异想天开,随心所欲,反复无常
wrench|n.扳钳,扳手,猛扭,痛苦,扭伤,歪曲vt.猛扭,使扭伤,曲解,抢,折磨vi.猛扭,绞痛
ornithological|adj.鸟类学的adj.鸟类学的
plume|n.羽毛
repel|vt.击退,抵制,使厌恶,使不愉快
party|n.党,政党,随行人员,[律]当事人,社交会
dramatist|n.剧作家
askance|adv.斜,斜视
slate|n.板岩,石板,石片,蓝色adj.暗蓝灰色的,含板岩的v.铺石板
circumlocution|n.婉转曲折的陈述
instructor|n.教师,<美>讲师
abscission|n.切断,除去
physicist|n.物理学者,唯物论者
refresh|v.(使)精神振作,(使)精力恢复,更新
moronic|adj.低能的,鲁钝的
promissory|adj.允诺的,约定的,有约束力的
beatific|adj.祝福的,快乐的,幸福的
sacrosanct|adj.极神圣的
marked|adj.有记号的,显著的
cheat|n.欺骗,骗子v.欺骗,骗取
gustation|n.尝味,味觉
reek|n.<主苏格兰>烟,水蒸汽,雾,臭气vi.冒烟,发臭气,散发vt.用烟熏,散发
fallible|adj.易错的,可能犯错的
faucet|n.龙头,旋塞,(连接管子的)插口
approachability|n.可接近,易接近
flabbiness|n.软弱,无气力
movement|n.运动,动作,运转,乐章
provender|n.粮草,秣,[口]食物
scratch|n.乱写,刮擦声,抓痕,擦伤vt.乱涂,勾抹掉,擦,刮,搔,抓,挖出vi.发刮擦声,搔,抓adj.打草稿用的,凑合的
peripheral|adj.外围的n.外围设备
hapless|adj.倒霉的,不幸的
sociability|n.好交际,社交性,善于交际
trammel|n.拘束,阻碍物,束缚物vt.拘束,阻碍,束缚
hinder|adj.后面的v.阻碍,打扰
eaglet|n.小鹰
ameliorate|v.改善,改进
commencement|n.开始,毕业典礼
genuflect|v.屈服
incursion|n.袭击,侵入
gruelling|使人精疲力尽
student|n.(大小学校的)学生,研究者,学者
greenhouse|n.温室,花房
anarchist|n.无政府主义者
affronted|adj.被侮辱的,被冒犯的
unorthodox|adj.非正统的,异教的,异端的
bored|adj.无聊的,无趣的,烦人的
eucalyptus|n.[植]桉树
beguiling|adj.欺骗的,消遣的
reconsideration|n.再考虑,再审议,新审议
nethermost|adj.最底下的,最下面的
grandiosity|n.宏伟,夸张,堂皇
distillation|n.蒸馏,蒸馏法,蒸馏物,精华,精髓
rectification|n.纠正,整顿,校正,精馏,整流
depredate|v.掠夺,毁坏
jury|n.[律]陪审团,评判委员会,陪审员adj.[海]临时应急的
bode|v.预示vbl.忍耐
equalize|vt.使相等,补偿
crevasse|n.破口,崩溃处,裂缝vt.使有裂缝
knavery|n.流氓行为
behavior|n.举止,行为
soil|n.土壤,土地,国土,国家,温床,粪便,务农vt.弄脏,污辱vi.变脏
amble|vi.缓行,溜蹄
bumpkin|n.土包子,乡巴佬
intensify|vt.加强vi.强化
missal|n.弥撒用书
friendship|n.友谊,友好
absolute|adj.完全的,绝对的
balk|n.障碍,梁木v.妨碍,(马)不肯前进
curdle|v.凝固
discrepancy|n.相差,差异,矛盾
self-evident|adj.自明的,不证自明的,不言而喻的
assess|vt.估定,评定
infection|n.[医]传染,传染病,影响,感染
zipper|n.拉练
rowdily|
understanding|n.谅解,理解
paralytic|adj.瘫痪的n.瘫痪病人
sextant|n.六分仪,<罕>圆的六分之一
crop|n.农作物,产量,平头,短发vt.收割,修剪,种植vi.收获
advise|vt.劝告,忠告,警告,建议
principally|adv.主要地
scurry|vi.急赶,急跑,急转,以轻快而交替的步子走动n.急赶,急跑,急转
ameliorate|v.改善,改进
detach|vt.分开,分离,分遣,派遣(军队)
slither|vi.不稳地滑动vt.使滑动
asset|n.资产,有用的东西
draft|n.草稿,草案,草图vt.起草,为...打样,设计v.草拟
declassify|vt.不再当机密文件处理,从机密表删除
reliant|adj.信赖的,依靠的,信赖自己的
alga|n.藻类,海藻
shading|n.留下阴影,描影法,明暗法,底纹,遮蔽
handgun|n.手枪
oppression|n.压迫,镇压,压抑,苦恼
watershed|n.分水岭
relax|vi.放松,休息,休养,变从容vt.使松驰,缓和,使松懈,使休息
removable|adj.抽取式的,可移动的
transplant|v.移植,移种,移民,迁移n.移植,被移植物,移居者
fingernail|n.手指甲
excavation|n.挖掘,发掘,挖掘成的洞,出土文物
homogenize|vi.均质化vt.使均匀
evergreen|adj.常绿的n.常绿树,常绿植物
palaver|n.谈判,交涉,闲聊vi.谈话(谈废话),阿谀vt.阿谀,哄骗
piquant|adj.开胃的,辛辣的,泼辣的,兴奋的,顽皮的,淘气的
permissive|adj.许可的
acidity|n.酸度,酸性,[医]酸过多,胃酸过多
asthmatic|adj.哮喘的,患哮喘症
balmily|
is|prep.是[域]Iceland,冰岛abbr.[军]InternalSecurity,治安
scare|v.惊吓,受惊,威吓n.惊恐,恐慌,恐惧
trident|n.三叉戟式飞机
vintner|n.葡萄酒商
diabetes|n.[医]糖尿病,多尿症
reverberate|v.反响
bounty|n.慷慨,宽大,施舍,奖励金
acute|adj.敏锐的,[医]急性的,剧烈
trance|n.恍惚,出神,着迷,[医]迷睡vt.使恍惚,使发呆
foreboding|n.预感,先兆,预兆adj.预感的,预兆的,不祥之兆的
lethal|adj.致命的n.致死因子
scarp|n.悬崖vt.使成陡坡
inland|adj.内陆的,国内的adv.在内地,向内地n.内地
cavern|n.巨洞,洞窟,深处vt.放于山洞中,挖空
ribbon|n.缎带,丝带,带,带状物,带子
proceed|vi.进行,继续下去,发生
iciness|n.冰冷的性质,冰冷,如冰
tower|n.塔,城堡
surefire|adj.准不会有错的,一定能达到目的的
mole|n.[医]胎块,[动]鼹鼠,防波堤,筑有防波堤的海港
reluctance|n.不愿,勉强
irrefragable|不能否定的,不可争辩的adj.不能反驳的
outbreak|n.(战争的)爆发,(疾病的)发作
anti|n. 反对者，反对论者
gnawing|n.咬,苛责,不断的苦痛adj.咬的,使苦恼的
levity|n.轻率,轻浮,不稳定,多变
quorum|n.法定人数,选出的团体
determinant|adj.决定性的
distend|v.(使)扩大,(使)扩张
cloture|n.讨论终结vt.结束辩论
synthetically|adv.综合地,合成地
epizootic|adj.流行于家畜的,体外寄生的n.家畜流行病
mecca|n.众人渴望去的地方
meaning|n.意义,含意,意图,[逻]内涵adj.意味深长的
pebble|n.小圆石,小鹅卵石
daze|vt.使茫然,发昏,使晕眩n.迷惑,眼花缭乱
emerald|n.[矿]祖母绿,翡翠,绿宝石,翠绿色adj.翡翠的,翠绿色的
microscopically|用显微镜
cultivate|vt.培养,耕作
provision|n.供应,(一批)供应品,预备,防备,规定
concordat|n.协定,宗派间的协约
lattice|n.格子
indulgence|n.放任
scatterbrain|n.注意力不集中的人
schoolmistress|n.女教师(员),女校长
backward|adv.adj.向后地(的),相反地(的),追溯,退步,由好变坏
irreverent|adj.不尊敬的
tint|n.色彩
grating|n.门窗的栅栏,[物理]光栅,摩擦,摩擦声adj.刺耳的
faddy|adj.追随时尚的,流行的
jitter|vi.<美口>紧张不安,战战兢兢
scripture|n.手稿,文件,[Scripture]基督教(圣经),经文
molester|烦恼
adult|n.成人,成年人adj.成人的,成熟的
polytheistic|adj.多神教的,信奉多神教的
dissimulate|v.掩饰,假装,装糊涂
foretaste|n.预示
intrigued|激起的兴趣
buckle|n.带扣v.扣住,变弯曲
climactic|adj.顶点的,渐层法的,高潮的
intuit|v.由直觉知道
valueless|adj.不足道的
handkerchief|n.手帕
caliper|n.测径器,卡钳,弯脚器vt.用卡钳测量
referable|可归咎于...,可交付的
yours|pron.你的,你们的
sportive|adj.嬉戏着的,欢闹的,开玩笑的,运动的,好色的
coddle|vt.娇养,溺爱,煮蛋n.娇生惯养的人,身体虚弱的人
domesticate|vt.驯养,使安于土地,教化
headdress|adj.饰头巾,头发编梳的式样
ellipse|n.[数]椭圆,椭圆形
paucity|n.极小量
upswing|n.高涨,向上摆动,改进vi.向上摆动,提高
burgher|n.公民,市民(现主要指某些欧洲国家中产阶级的市民或镇民)
currish|adj.野狗似的,恶意的,爱吵闹的
nervousness|神经过敏
afterwards|adv.然后,后来地
quash|v.取消
rotate|v.(使)旋转
sonnet|n.十四行诗,商籁体
luggage|n.行李,皮箱
ruler|n.统治者,管理者,尺,直尺n.标尺,划线板,划线的人
protrusive|adj.推出的,突出的,凸出的
pane|n.长方块,尤指窗格,窗格玻璃,边,面
sprocket|n.链轮齿
wig|n.假发
compress|vt.压缩,摘要叙述n.(外科)敷布
lesion|n.损害,身体上的伤害
metronome|n.节拍器
liberate|v.解放,释放
transport|n.传送器,运输,运输机,激动,流放犯,狂喜vt.传送,运输,流放,放逐
Dacron|达可纶
decalogue|
liberal|n.自由主义者,(尤指英国、加拿大等国的)adj.慷慨的,不拘泥的,宽大的,自由主义的
binding|n.装订,捆绑,捆绑物,粘合物
impair|v.削弱
dinosaur|n.恐龙
soot|n.煤烟,烟灰v.用煤烟弄脏
varicose|adj.[医]肿胀的,曲张的
benignly|adv.仁慈地,亲切地
allegiance|n.忠贞,效忠
visualize|vt.形象,形象化,想象vi.显现
dismissal|n.免职,解雇,不予考虑
rich|adj.富的,有钱的,富有的,富饶的,肥沃的,充足的,丰富的
hurried|v.催促adj.匆忙的
serf|n.农奴,奴隶
obsequiousness|
industry|n.工业,产业,行业,勤奋
golf|n.高尔夫球vi.打高尔夫球
intruder|n.入侵者
overthrow|n.推翻,打倒,扔得过远得球vt.打倒,推翻,颠覆
enforcement|n.执行,强制
splashy|adj.易溅的,泼溅的,有色斑的
wintriness|n.如冬天的寒冷,冷淡
goods|n.货物,<美俚>工具
pleonasm|n.烦冗,冗长
knuckle|n.指节,关节
plagiarist|n.剽窃者,文抄公
frigate|n.三帆快速战舰,护卫舰
dress|n.女服,童装,服装,衣服v.(给...)穿衣
pulley|n.滑车,滑轮
grasshopper|n.蚱蜢,蝗虫,小型侦察机
coxswain|n.艇长,舵手
exchequer|n.[英史]财物署,国库,财源,财政部
genially|adv.亲切地,快活地,和蔼地
parenthetically|作插句
truss|vt.捆绑n.(干草的)一捆,一束,构架
iguana|n.[动]鬣蜥(一种产于南美洲和西印度群岛的大蜥蜴)
venison|n.野味,鹿肉
bellow|v.(牛,象等)吼叫,怒吼,咆哮
arrest|vt.逮捕,拘留,吸引n.逮捕,拘留
sprung|vbl.spring的过去式及过去分词
forfeit|n.(因犯罪.过失.违约等而)丧失的东西,没收物,罚款vt.没收,丧失adj.丧失了的
rollicking|adj.嬉戏耍闹作乐的
portable|adj.轻便的,手提(式)的,便携式的
percolator|n.过滤器,抽出器
intellect|n.智力
habit|n.习惯,习性
plea|n.恳求,请求,辩解,藉口
adventurism|n.(外交,政治等方面的)冒险主义
dictionary|n.字典,词典
proselytizer|
advise|vt.劝告,忠告,警告,建议
graphite|n.石墨
depraved|adj.堕落的,颓废的,邪恶的
chimera|n.[希神]狮头,羊身,蛇尾的吐火怪物,妖怪,狂想
demography|n.人口统计学
applicant|n.申请者,请求者
reminiscence|n.回想,记忆力,怀旧
pacifist|n.和平主义者
instalment|n.分期付款,就职,装设
shale|n.[地]页岩,泥板岩
operator|n.操作员,工作者,(电话)接线员,报务员,手术员,行家,经营者,算子
extermination|n.消灭,根绝
prove|vt.证明,证实,检验,考验vi.原来(是),证明(是)
adjudicate|v.判决,宣判,裁定
concealment|n.隐藏,隐蔽,隐蔽处
discrete|adj.不连续的,离散的
bafflement|n.阻碍,迷惑
whirlpool|n.漩涡,涡流,混乱,纷乱
dockyard|n.造船所,修船所
surrender|vt.交出,放弃,使投降,听任vi.投降,自首n.交出,放弃,投降投降算了
consumer|n.消费者
wrangle|vi.争论,争吵,口角vt.辩驳,放牧n.口角,吵嘴
August|n.八月
spray|n.喷雾,飞沫vt.喷射,喷溅
tabulation|n.作表,表格
heedless|adj.不注意的
fraternal|adj.兄弟的,兄弟般的,友爱的
evoke|vt.唤起,引起,博得
designer|n.阴谋家,设计家,制图师
behold|vt.把...视为vi.看
encomiast|n.宣读或写颂辞之人,阿谀者,赞美者
trinity|n.三位一体,三人一个组,三个一组的(物)
supernal|adj.天上的,神的,高的,超自然的
resiliency|n.跳回,弹性
enlargement|n.放大
son|n.儿子,女婿,(长者对年轻男子的称呼)孩子
military|adj.军事的,军用的
mythologize|vt.讲神话,编神话vi.写神话,给神话分类
domestically|adv.家庭式地,合乎国内地
natal|adj.出生的,诞生的
conspiracy|n.共谋,阴谋
solo|n.独奏曲adj.单独的
differ|vi.不一致,不同
lifelike|adj.逼真的
alkalinity|n.[化]碱度
sketchy|adj.粗略的
thumb|n.拇指vt.以拇指拨弄,笨拙处理,弄坏,翻阅,作搭车手势vi.用拇指翻书页
bode|v.预示vbl.忍耐
trout|n.[鱼]鲑,鲑鱼
unfounded|adj.没有理由的,未建立的
locative|adj.位置格的n.位置格,位置格的词
amusing|adj.有趣的
pacification|n.讲和,和解,平定
gnomic|adj.格言的,含格言的
ours|pron.我们的
gluttony|n.暴食,贪食
bedroom|n.卧室
decision|n.决定,决心,决议,结果,果断,坚定
dispatch|vt.分派,派遣n.派遣,急件
steal|v.偷,窃取,偷窃,偷盗
incriminatory|adj.负罪的,成为有罪的
prodigious|adj.巨大的
foppery|n.纨绔习气
contraceptive|adj.避孕的n.避孕品,避孕用具
gladiator|n.古罗马公开表演的格斗者(通常都是奴隶和俘虏),精于辩论和格斗的人,职业拳击者
transpose|vt.调换,颠倒顺序,移项vi.进行变换n.[数]转置(矩)阵
eruption|n.爆发,火山灰,[医]出疹
carbonated|充了碳酸气的-ting
off|adj.远的,空闲的,不工作的adv.离开,在远方,离去,分离,中断,完成prep.从...离开,脱离
ambulance|n.战时流动医院,救护车
region|n.区域,地方,(世界上某个特定的)地区,(艺术,科学等的)领域,(大气,海水等的)层
reassure|vt.使...安心,再保证,使...恢复信心,打消...的疑虑
unfocussed|
him|pron.他
inflation|n.胀大,夸张,通货膨胀,(物价)暴涨
blowed|吹
ale|n.淡色啤酒(较一般啤酒含更多的酒精)
clavicle|n.[解剖]锁骨
embarrassment|n.困窘,阻碍
languish|vi.憔悴,凋萎,衰退,苦思
apex|n.顶点
bevel|n.斜角,斜角规,倾斜,斜面vi.成斜角vt.使成斜角
spasm|n.(感情等)一阵发作,痉挛
maid|n.少女,女仆
sphinx|[Sphinx][希神]斯芬克斯(有翼的狮身女怪,传说她常叫过路行人猜谜,猜不出者即遭杀害)
jeopardize|v.危害
tiptoe|n.脚尖,趾尖vi.用脚尖走
mother|n.母亲,妈妈
maxim|n.格言,座右铭
craggy|多峭壁的,崎岖的
stirrup|n.马镫,镫形物
worth|prep.相当...价值n.价值,财产adj.值钱的,值的看中的
imperfection|n.不完整性,非理想性
oversee|v.俯瞰,监视,检查,视察
joke|n.笑话,玩笑v.(和...)开玩笑
summarization|n.摘要,概要
firstborn|adj.头生的(子女),初生的,第一胎生的n.初生儿,长男,长女
minaret|n.尖塔
depredate|v.掠夺,毁坏
unfeigned|adj.真实的
heat|n.热,热度,热烈,高潮,压力vi.加热,激昂,发热,发怒vt.把...加热,使激动abbr.[军]HighExplosive-Anti-Tank,破甲弹
select|vt.选择,挑选adj.精选的
naivete|n.天真烂漫,纯真无邪
detour|n.便道,绕路vi.绕路而行vt.使绕道
proselyte|n.改信仰者vt.使改宗教信仰vi.改变宗教信仰
snowstorm|n.暴风雪
jugular|adj.喉的,颈的,颈静脉的n.颈静脉
rebut|v.反驳
mistrustfully|多疑
leg|n.腿,胫,旅程的一段vi.走,跑
instigate|v.鼓动
indissoluble|adj.不能分解的
buoy|n.(湖,河等中的)浮标,浮筒,救生圈vt.使浮起,支撑,鼓励
justice|n.正义,正当,公平,正确,司法,审判,欣赏
plausibly|adv.似真地
legitimated|
blight|n.枯萎病,不良影响,打击vt.破坏,使枯萎
centripetal|adj.向心的，利用向心力的
always|adv.总是,永远,始终
lough|n.<爱尔兰>湖,港湾
filth|n.污秽,污物,不洁,猥亵
murky|adj.黑暗的
efface|v.抹掉
surefire|adj.准不会有错的,一定能达到目的的
sophisticated|adj.诡辩的,久经世故的
autumn|n.秋天,成熟期,渐衰期
privateer|n.(战时特准攻击敌方商船的)武装民船,私掠船
dawdler|n.游手好闲的人,懒人
sharpener|n.削刀,磨床,磨器,磨具
manufacture|vt.制造,加工n.制造,制造业,产品
imbibe|v.吸收
dismally|adv.阴暗地,沉闷地
transcendence|n.卓越,出类拔萃
recommend|vt.推荐,介绍,劝告,使受欢迎,托付,使...受欢迎,使...可取
utter|adj.全然的,绝对的vt.发出,做声,发表,发射,流通
forebear|n.祖先,祖宗
threnody|n.悲歌,哀歌
tectonics|n.筑造学
blanket|n.毯子vt.覆盖
commissariat|n.军需部门,粮食,粮食补给
inactive|adj.无行动的,不活动的,停止的,怠惰的adj.非活动的
price|n.价格,价钱,代价vt.给...定价,问...的价格,标明价格
tined|有齿的,有叉的
hairiness|n.有毛,多毛的性质或状态
satisfaction|n.满意,满足,令人满意的事物
poll|n.选举之投票,民意测验v.投票,获得选票,选举中获得
imply|vt.暗示,意味
expedient|adj.有利的n.权宜之计
disconcerted|adj.不安的,惊慌的
hound|n.猎犬vt.带猎犬狩猎,卑鄙的人,追捕,激励,使追逐
revision|n.修订,修改,修正,修订本
synthetically|adv.综合地,合成地
mummy|n.[小儿语]妈咪,[口头语]妈妈,木乃伊,干瘪的人
reporter|n.记者,通讯员
pocket|n.衣袋,口袋,钱,财vt.装...在口袋里,隐藏(感情),据为己有,击...入袋adj.袖珍的,小型的
prodigal|adj.浪费的n.浪子
farmer|n.农夫,百姓,农民,农场主,承包主,牧场主,畜牧者
insistently|adv.坚持地,强求地
murkily|adv.黝暗地,阴沉地
inanition|n.空洞,无意义,浅薄,愚蠢
phosphorous|adj.磷的
antediluvian|adj.(《圣经》中所说的)大洪水前的,上古的,古风的n.大洪水以前的人,很老的人,老古董
contraposition|n.对置,对位,对照
footwear|n.<美>鞋类(鞋,靴,拖鞋等)
psyche|n.1.心智2.灵魂；精神
infestation|n.(害虫,盗贼等)群袭,出没,横行
stencil|n.模版,蜡纸vt.用蜡纸印刷
demulcent|adj.缓和的,镇痛的n.镇痛剂,缓和剂
pipeline|n.管道,传递途径
spotless|adj.没有污点的
compatibly|adv.和气地,适合地
superimposition|n.叠印
commiserate|v.怜悯,同情
rapidity|n.速度,迅速,急速
sully|v.玷污
alleviation|n.缓和
baseless|adj.无根据的
stricken|v.(strike的过去分词,见strike)adj.被打中的,遭殃的,患病的
retributive|adj.报应的
rice|n.稻,米
currently|adv.普遍地,通常地,现在,当前
guillotine|n.断头台,(切纸的)闸刀v.处斩刑,切(纸)
conflict|n.斗争,冲突vi.抵触,冲突
threadlike|adj.线状的
stereotype|n.[印]铅版,陈腔滥调,老套vt.使用铅版,套用老套,使一成不变
salute|n.(尤指军队等之)举手礼,升降旗致敬,呜礼炮等,敬礼v.行礼致敬,敬礼
buggy|adj.多虫的,臭虫成灾的,<俚>神经病的n.<美>童车,<俚>尤指旧汽车,双轮单座的轻马车
pedagogy|n.教学,教授,教育学
uptodate|adj.直到现代的,现时的,最新式的
leafless|adj.无叶的
dissimilar|adj.不同的,相异的
brimstone|n.硫黄
unyoke|vt.卸除轭,解除束缚,解开vi.停止工作
thematic|adj.词干的,题目的,主题的,论题的
unfortunate|adj.不幸的,不合宜的,不吉利的,使人遗憾的n.不幸的人
magnitude|n.大小,数量,巨大,广大,量级
kindergarten|n.幼儿园adj.幼儿园的,初级的,启蒙阶段的
blur|v.涂污,污损(名誉等),把(界线,视线等)弄得模糊不清,弄污n.污点
bequeath|vt.遗赠,遗留,把...传下去
maiden|n.少女,处女adj.未婚的,纯洁的,处女的,无经验的
ripen|vt.使成熟vi.成熟
entrepot|n.<法>仓库,贸易中心
appreciative|a欣赏的,有欣赏力的,表示感激的,承认有价值的
planisphere|n.平面天球图,星座图
marvel|n.奇迹v.大为惊异,觉得惊奇
cheetah|n.[动]印度豹（一种似豹的动物,产于南亚及非洲）
barb|n.鱼钩,鱼叉的倒钩,巴巴里鸽(一种类似信鸽的鸽子)vt.装倒钩于
wealthy|adj.富有的,丰裕的,充分的n.富人,有钱人
sardonically|讥讽
pushy|adj.有进取心的
irregularly|adv.不规则地
insubordination|n.不顺从,反抗
scad|n.[鱼]竹荚鱼,<美口>许多
gambler|n.赌博的人,赌徒
decidability|
return|n.回来,返回,来回票,利润,回答adj.返回的,回程的,报答的,反向的,重现的vi.回返,归还vt.归还,回报,报告,获得,回答,返回
bibliomania|n.藏书癖,藏书狂
salvage|n.抢救财货,获救的财货,救难的奖金,海上救助,抢救,打捞vt.海上救助,抢救,打捞,营救
tacky|adj.有些粘的,缺乏教养或风度的,俗气的
employ|vt.雇用,用,使用v.使用n.雇用
centiliter|n.厘升
self-sufficient|adj.自给自足的,过于自信的
bibliographer|n.书志学家,书目提要编著人
angular|adj.有角的
genealogically|家系
starter|n.起动器,起动钮
conjugal|adj.结婚的,夫妇间的
faulty|adj.有过失的,有缺点的,不完美的,不完善的
pestle|n.乳钵,槌,杵v.用槌磨,用杵捣
swift|n.[鸟]雨燕,(梳棉机等的)大滚筒adj.迅速的,快的,敏捷的,立刻的adv.迅速地,敏捷地
symmetric|adj.相称性的,均衡的
initiate|vt.开始,发动,传授v.开始,发起
upshot|n.结果
poultry|n.家禽
odometer|n.<美>(汽车等的)里程表
elocutionary|adj.雄辩术的,演说法的
alimony|n.[律](离婚或分居后在诉讼期间男方给女方的)赡养费,生活费
electorate|n.选民,选区,有选举权者
invoke|v.调用
arid|adj.干旱的,贫瘠的(土地等),无趣的,沉闷的
enlarge|v.扩大,放大
sagacious|adj.有洞察力的,有远见的,精明的,敏锐的
indemnity|n.保证物,赔偿物,赔款,补偿,保证
inure|vt.使习惯vi.生效
transcendental|adj.先验的,超越的,超出人类经验的
snivel|v.流鼻涕n.啜泣
colloquium|n.讨论会
polarization|n.[物]偏振(现象),极化(作用),两极化,分化
futility|n.无益,无用,轻浮的言行
combative|adj.好战的,杀气的,好斗的
brigand|n.土匪,强盗,歹徒(常指流窜帮中的一员)
slippage|n.滑动,滑移,滑程
salivate|v.过量分泌唾液
madrigal|n.小曲
self-respect|n.自尊,自重
irritably|adv.性急地,暴躁地
done|adj.妥当的,合乎礼仪的,完成了,做好了的,注定要完蛋的vbl.做(do的过去分词)
mistily|adv.有雾地,朦胧地,不清楚地
scrutinize|细察
besiege|vt.围困,围攻,包围
absolution|n.免罪,赦免
local|adj.地方的,当地的,局部的,乡土的n.当地居民,本地新闻,慢车,局部
rentable|adj.可出租的
herbicide|n.除草剂
boy|n.男孩,儿子,孩子气的人,男仆
impound|vt.关在栏中,拘留,扣押,没收
ramose|adj.多枝的,分枝的
concave|adj.凹的,凹入的n.凹,凹面
pettily|adv.卑鄙地,小气地
lid|n.盖子,<美口>限制,眼睑vt.给...盖盖子
steel|n.钢,钢铁
seer|n.预言家,先知者,幻想家
reverie|n.幻想
sea|n.海洋,大浪,大量,许多
stipend|n.薪金,定期生活津贴
file|n.文件,档案,文件夹,卷宗,锉刀vt.把...归档,提出(申请等),锉,琢磨vi.列队行进,用锉刀锉
tactless|adj.不老练的
cheerless|adj.不快活的
joyful|adj.快乐的,兴高彩烈的,可喜的,令人欢欣的
envisage|v.正视
idol|n.偶像,崇拜物,幻象,[逻]谬论
violinist|n.小提琴演奏者,小提琴家
muted|减弱
chameleon|n.变色龙
inedible|adj.不适于食用的,不能吃的
southward|adv.向南adj.向南的
Grammy|Grammy Awards 格莱美奖 ; 葛莱美奖 ; 格莱美音乐奖 ; 格莱美音乐大奖
disband|v.解散,裁减
overcoat|n.外套大衣
indefensible|adj.不能防卫的,无辩护余地的
shortly|adv.立刻,不久,简略地,简言之,即刻
desultoriness|n.散漫
endearingly|
untie|vt.解开,解放,解决vi.松开,解开
consensus|n.一致同意,多数人的意见,舆论
trip|n.(短途)旅行,绊倒,摔倒,失足,往返,差错,支吾,旅程vt.使跌倒,使犯错,使失败,挑剔vi.轻快地走,摔倒,绊倒,失足,结巴,远足,犯错,旅行
policewoman|n.女警官,女警察
penitent|adj.悔过的n.悔罪者
dilatorily|adv.慢吞吞地,迟缓地
dead|adj.死的,无感觉的,呆板的,不流动的,(语言、习惯)废弃了的,熄灭的n.死者adv.完全地,绝对的,突然的
animate|v.鼓舞adj.生气勃勃的
sanctuary|n.避难所
acrophobia|n.[医]恐高症
patio|n.天井,院子
impeachment|n.弹劾,指摘
overgrown|adj.簇叶从生的,长得太大,畸形发展的
vicissitude|n.变迁兴衰
tapestry|n.织锦,挂毯vt.编织锦或织画,用挂毯装饰
exclude|vt.拒绝接纳,把...排除在外,排斥
premiere|v.初次公演,初演主角n.初次的演出adj.突出的,杰出的
Sam|sam
palatably|adv.美味地,称心愉快地
longevity|n.长命,寿命，供职期限，资历
upright|adj.垂直的,竖式的,正直的,诚实的,合乎正道的adv.笔直,竖立着n.垂直,竖立
disciplinarian|adj.训练的,规律的,训育的n.训练者,规律,厉行纪律的人
putrefaction|n.腐败,腐败物
custard|n.奶油蛋羹,奶油冻
reign|vi.统治,支配,盛行,占优势n.统治,统治时期,支配
seer|n.预言家,先知者,幻想家
candle|n.蜡烛vt.对着光检查
monsieur|n.先生,绅士
purposefully|有目的地,自觉地
roundabout|adj.迂回的,转弯抹角的n.道路交叉处的环形路,迂回路线,兜圈子的话
yummy|n.美味
vivacity|n.活泼
murkily|adv.黝暗地,阴沉地
extroverted|adj.外向性的,喜社交的
merit|n.优点,价值v.有益于
scorpion|n.[动]蝎子,心黑的人,蝎子鞭,<俚>直布罗陀人
tyrant|n.暴君
pope|n.罗马教皇,主教,蒲柏(1688-1744,英国诗人),大腿上要害部位vt.打大腿上要害部位
avoidable|adj.可避免的
disablement|n.无力化,无能力
statute|n.法令,条例
tableau|n.生动的场面,戏剧性局面
advisory|adj.顾问的,咨询的,劝告的
cosmopolitanism|n.世界大同主义,四海一家
tuba|n.大号,风琴音栓之一种
form|n.形状,形态,外形,表格,形式v.形成,构成,排列,(使)组成
valueless|adj.不足道的
absentminded|adj.心不在焉的,茫然的,恍惚的
reflective|adj.沉思的
butter|n.黄油,牛油vt.涂黄油于...上
bungle|v.办糟
shadowy|adj.有阴影的,多荫的,阴凉的
crutch|n.(跛子用的)拐杖,支撑,帮助vt.支撑
stain|n.污点,瑕疵v.染污,沾污
competence|n.能力
rehabilitate|v.使(身体)康复,使复职,使恢复名誉,使复原
enshrine|vt.入庙祀奉,铭记
demagog|n.煽动家,群众领导者
excellent|adj.卓越的,极好的
cleanly|adj.喜清洁的,干净的,洁净的adv.干净地,清洁地,清白地
asunder|adv.分离,成碎片
designedly|adv.故意地,特意地,有计划地
self-analysis|n.自我心理分析
goodwill|n.善意,亲切
transmission|n.播送,发射,传动,传送,传输,转播
titanium|n.[化]钛
itinerant|adj.巡回的n.巡回者
ruefully|adv.悲伤地,可怜地
islet|n.小岛
polygamy|n.一夫多妻,一妻多夫
currency|n.流通
gerrymander|vt.为本党利益改划选举区分vi.不公正操纵,欺骗n.改变选举区,欺骗
lump|n.块（尤指小块）,肿块,笨人vt.使成块状,混在一起,忍耐,笨重地移动vi.结块
carbon|n.[化]碳(元素符号C),(一张)复写纸
calumniate|vt.中伤,诽谤
excessively|adv.过分地,非常地
debar|v.阻止,禁止,排除,剥夺
touchdown|n.[美橄]攻方持球,触地,触地得分,着地,降落
admiring|adj.赞赏的,钦佩的
posthumous|adj.死后的,身后的,作者死后出版的,遗腹的
defeatist|n.失败主义者
snow|n.雪vi.下雪
yank|v.n.猛拉
concise|adj.简明的,简练的
lipstick|n.<美>口红,唇膏
humanitarian|n.人道主义者
controllable|adj.可管理的,可操纵的,可控制的
German|n.德国人,德语adj.德国的,德国人的,德语的
drainage|n.排水,排泄,排水装置,排水区域,排出物,消耗
carafe|n.玻璃水瓶
sprout|v.萌芽n.苗芽
intense|adj.强烈的,剧烈的,热切的,热情的,激烈的
quote|vt.引用,引证,提供,提出,报(价)
sparsely|adv.稀疏地,稀少地
plutonium|n.[化]钚
kingdom|n.王国,[宗]天国,上帝的统治,领域
eyeball|n.眼球,眼珠子
somnolent|adj.想睡的,催眠的
dissembler|n.伪君子,伪善者
sententious|adj.简洁的,警句的,富于格言的,很多(过分)说教式的
moody|adj.喜怒无常的,忧悒的
transfusion|n.注入,[医]输血,输液
lavish|adj.非常大方的,过分丰富的,浪费的vt.浪费,滥用,慷慨给予
nun|n.修女,尼姑
relate|vt.叙述,讲,使联系,发生关系
nee|adj.旧姓的,娘家姓的
skilful|adj.巧妙的,技术好的
adventurous|adj.喜欢冒险的,敢做敢为的,充满危险的
enfeeble|vt.使衰弱
dilettantish|adj.(在艺术、科学等方面)半吊子的,半瓶醋似的,一知半解的,浅薄的业余爱好的
inquire|v.询问,问明,查究
deep|adj.深的,纵深的,远离中心的,深奥的,难懂的,(指人)诡计多端的,低沉的(声音)adv.深入地,迟n.深渊,深处
misunderstanding|n.误会,误解
arena|n.竞技场,舞台
unpretentious|adj.不骄傲的,谦逊的
daily|adj.每日的,日常的adv.每日,日常地,天天n.日报,<美口>朝来夜去的女佣
respite|n.暂缓v.暂缓
foreground|n.前景,最显著的位置
gynecoid|adj.<美>gynaecoid
granny|n.奶奶
revenge|n.报仇,复仇vt.替...报仇,复仇
sticky|adj.粘的,粘性的
normalize|v.规格化
monomania|n.对一事的热狂,偏执狂
inherence|n.(性质等的)内在,固有,天赋,[哲]内在性,固有性(指属性对于主体的关系)
martyr|n.烈士,殉教者v.杀害,折磨
literate|n.学者adj.有文化的，有阅读和写作能力的
salutary|adj.有益的
plastered|adj.醉醺醺的
fortunately|adv.幸运地
sulky|adj.生气的,阴沉的
pulverize|v.研磨成粉
callow|adj.年轻而无经验的,(鸟)未生羽毛的
physic|n.医学,医术,泻药vt.给...服药,治愈
infertile|adj.不肥沃的,贫瘠的,不毛的,不结果实的
animosity|n.仇恨,憎恶
doubtless|adj.无疑的,确定的adv.无疑地,确定地,<口>大概、多半
sere|adj.干枯的n.演替系列
fordable|可以涉水而过的
doorway|n.门口
gargantuan|adj.巨大的,庞大的
immolation|n.宰杀,祭物
jeweller|n.珠宝商,宝石匠,钟表匠
dandified|adj.打扮得华丽的
positivism|n.确定,自信,[哲]实证论,实证主义
sneer|v.冷笑,讥笑,嘲笑n.冷笑,嘲笑
subway|n.地道,<美>地铁
hypothetically|adv.假设地,假想地
drift|n.冲洗,漂流物,观望,漂流v.(使)漂流
rogue|n.流氓,无赖vt.欺诈vi.流浪,耍无赖,游手好闲
positivist|n.实证哲学家,实证主义者
slay|v.<书>杀,杀死,宰杀,杀害,宰杀,杀死
feudalism|灭亡
fungible|adj.可互换的,代替的n.代替物
capture|n.捕获,战利品vt.俘获,捕获,夺取
disqualify|vt.使丧失资格
dish|n.盘,碟,盘装菜v.提出碟形卫星天线
taciturn|adj.沉默寡言的
monotone|adj.单调的n.单调
pager|n.呼机,寻呼机
fortune|n.财富,运气,大量财产,好运,命运vt.<古>偶然发生vt.给...以大宗财富
uncomplicated|adj.简单的，不复杂的
hoard|v.储藏
crimson|adj.深红色的n.深红色
multimedia|n.多媒体,多媒体的采用
ladle|n.杓子,长柄杓vt.以杓舀取,(用杓)舀汤,不分对象予以赠送
bereavement|n.(亲人)丧亡
gamester|n.赌徒,赌棍,体育比赛中不屈不挠者
conditioner|n.调节者,调节装置
borrower|n.借用人,剽窃者
procession|n.行列,队伍
obscurity|n.阴暗,朦胧,偏僻,含糊,隐匿,晦涩,身份低微
sly|adj.狡猾的
postponement|n.延期,延缓
unexampled|adj.无前例的,无可比拟的
versatility|n.多功能性
focused|聚焦的
interpretative|adj.作为说明的,解释的
striate|adj.有条纹的,有细槽的vt.加条纹
pantechnicon|n.家具仓库,家具搬运车
dilatory|adj.拖拉的,不慌不忙的
mulatto|n.白黑混血儿adj.白黑混血儿的,黄褐色的
utopian|乌托邦主义
sediment|n.沉淀物,沉积
direful|adj.可怕的,悲惨的
charm|n.吸引力,(女人的)魔力,魅力,符咒vt.迷人,使陶醉,行魔法vi.用符咒,有魔力
impound|vt.关在栏中,拘留,扣押,没收
depravation|n.堕落
charily|adv.小心谨慎地,节俭地,俭省地
rehearse|vt.预演,排演,使排练,复述,练习,背诵,作假vi.排练,练习,演习
withdraw|vt.收回,撤消vi.缩回,退出v.撤退
depraved|adj.堕落的,颓废的,邪恶的
par|n.同等,(股票等)票面价值adj.票面的,平价的,平均的,标准的
tattered|adj.破烂的,褴褛的
expunge|v.擦去
megaphone|n.扩音器
zip|[计]一种程序压缩的档案文件格式n.拉链v.拉开或拉上
funicular|adj.索状的n.索道
worthily|adv.重要地,可敬地,正当地
calculator|n.计算机,计算器
acidulous|adj.多少带酸味的,不悦的
magnate|n.大资本家,巨头,富豪,要人,...大王
heck|n.饲草架
empire|n.帝国,帝权
carbon|n.[化]碳(元素符号C),(一张)复写纸
canon|n.教会法教规,教规,(基督教的)正典圣经(简称正经),一个作家的真作日本佳能公司
tattooist|文身的人
insubstantial|adj.无实质色,无实体的,非实在的,幻想的,不坚固的,脆弱的
environmentalism|n.环境保护论,环境论
biologist|n.生物学家
carnage|n.(尤指在战场上的)残杀,大屠杀,流血
finger|n.手指(尤指大拇指以外的手指),指状物,指针v.用手指拨弄,伸出
epilogue|n.结语,尾声,[戏]收场白
moonlighting|n.夜间活动,夜袭,(尤指在夜间)从事第二职业
monotheist|n.一神论者
abacus|n.算盘
ingrain|vt.生染,就原料染色,使根深蒂固adj.生染的,根深蒂固的n.生染的纤维,原料染色,本质
prognosticate|v.预言
grant|vt.同意,准予,承认(某事为真)～
requiem|n.[天主教]安灵祢撒,安灵曲,挽歌,悲歌
frothy|adj.起泡的,多泡的,空洞的
orifice|n.孔,口
denizen|n.居民
tear|n.破处,破缝,泪滴,眼泪,扯,飞奔,激怒vi.流泪,撕破,猛冲,飞奔,被撕破vt.扯,撕,撕破,戳破,拉掉,折磨,使分裂,撕掉
faddy|adj.追随时尚的,流行的
conspicuousness|显著，卓越，突出
full-fledged|adj.羽毛生齐的,有充分资格的,发育完全的
correctness|正确性
paid|vbl.pay的过去式和过去分词
gravity|n.地心引力,重力
nought|n.无,零
roadside|n.路旁adj.路旁的
consumer|n.消费者
evidently|adv.明显地,显然
ostracism|n.(古希腊)贝壳放逐法,放逐,排斥
applicant|n.申请者,请求者
nameless|adj.无名的,不知名的,匿名的,不可名状的,难以形容的
franchise|n.特权,公民权v.赋予特权,赋予公民权
vengefully|adv.复仇心切地
coefficient|n.[数]系数
sanguineness|
requisite|adj.需要的,必不可少的,必备的n.必需品
chilly|adj.寒冷的
nectarine|n.油桃
marvellous|adj.绝妙的；了不起的
grandness|n.宏伟,伟大,壮大
peninsula|n.半岛
propagate|v.繁殖,传播,宣传
qualms|疑惧
foursome|n.四人的一组,四人对抗赛adj.四人做的,由四组成的
straitlaced|adj.严格的,固执的,刻板的
substitution|n.代替,取代作用,代入法,置换
chantey|n.船夫曲,水手歌(亦作chanty或shanty)
fall|n.秋天,落下,瀑布,降低,落差,采伐量,堕落,下降vi.倒下,落下,来临,失守,变成,垮台,下跌,阵亡vt.<美><英方>击倒,砍倒(树木)adj.秋天的
nude|adj.裸体的,裸的,与生俱有的,无装饰的n.裸体画,裸体
fortuitous|adj.偶然的,幸运的
reagent|n.反应力,反应物,试剂
tedium|n.厌烦,沉闷
informative|adj.情报的,提供情报的,见闻广博的
reduction|n.减少,缩影,变形,缩减量,约简
diluted|无力的冲淡的
discombobulated|破坏
slender|adj.苗条的,微薄的,微弱的
hotpot|n.罐焖土豆烧肉
punctual|adj.严守时刻的,准时的
ecstatic|n.狂喜的人adj.狂喜的,心醉神迷的,入迷的
semicolon|n.分号(即“;”)
nonconformist|n.非国教徒,不遵奉英国国教的基督新教徒
vibration|n.振动,颤动,摇动,摆动
kingdom|n.王国,[宗]天国,上帝的统治,领域
formidably|adv.可怕地,难对付地,,强大地
linkage|n.联接
worn|adj.用旧的,疲倦的vbl.wear的过去分词
grating|n.门窗的栅栏,[物理]光栅,摩擦,摩擦声adj.刺耳的
off-key|adj.不平常的,走开的
affably|adv.殷勤地
pause|n.中止,暂停,休止符vi.暂停,中止,停顿,踌躇n.暂停n.DOS命令：暂停批文件处理,在继续处理之前等待按任一键
apotheosis|n.尊为神,神化,颂扬,崇拜,典范
laborious|adj.(指工作)艰苦的,费力的,(指人)勤劳的
joyous|adj.快乐的,高兴的
haystack|n.干草堆
actuate|vt.开动,促使
noiseless|adj.无声的,寂静的
refinement|n.精致,(言谈,举止等的)文雅,精巧
stupor|n.昏迷
holly|n.冬青树
northern|adj.北方的,北部的
pizza|n.比萨饼（一种涂有乳酪核番茄酱的意大利式有馅烘饼）
pentahedron|n.五面体
diminuendo|n.[乐]渐弱演奏(部分)adj.[乐]渐弱的adv.[乐]渐弱地
unpack|v.打开包裹(或行李等),卸货,揭开
gastritis|n.[医]胃炎
demulcent|adj.缓和的,镇痛的n.镇痛剂,缓和剂
mislead|vt.误导
enthusiast|n.热心家,狂热者
pastel|n.彩色蜡笔,彩色蜡笔画adj.彩色蜡笔的,柔和的
sallow|adj.菜色v.变成菜色
diner|n.用餐者
bishop|n.主教
decalogue|
truly|adv.真实地,不假
referent|n.指示物
contempt|n.轻视,轻蔑,耻辱,不尊敬,[律]藐视法庭(或国会)
stronghold|n.要塞,据点
arraign|vt.提问,传讯,责难
horoscope|n.占星,诞生时的星位
astrological|adj.占星的,占星术的
cartoon|n.(报刊上的)政治性漫画,讽刺画,卡通画,漫画(常有解说词)v.画漫画n.卡通片,动画片
augment|v.增加,增大n.增加
morphology|n.[生物]形态学、形态论,[语法]词法、词态学
self-sacrifice|n.自我牺牲,献身
aerial|adj.航空的,生活在空气中的,空气的,高耸的n.天线
floral|adj.植物群的,花似的,花的,植物的
cavalier|n.骑士,武士,对女人献殷勤,有礼貌的绅士
addict|vt.使沉溺,使上瘾n.入迷的人,有瘾的人
photographically|摄影
revenue|n.收入,国家的收入,税收
continence|n.自制,克制,节欲(尤指禁欲)
foliage|n.树叶,植物
housemaster|n.舍监
misogynist|n.[心]厌恶女人的人
dogmatically|独断
pillow|n.枕头,枕垫
kinetically|
venture|n.冒险,投机,风险v.冒险,冒昧,斗胆,胆敢(谦语)
vineyard|n.葡萄园
nebular|adj.星云的
almond|n.[植]杏树,杏仁,杏仁壮物
consequence|n.结果,[逻]推理,推论,因果关系,重要的地位
bombard|vt.炮轰；轰击
prickle|n.刺,刺痛,柳条篮子v.刺,扎,戳
clumsy|adj.笨拙的
belly|n.腹部,胃vi.涨满
write|vt.书写,著述,写,写满,写信给vi.写,写字,写信,写作,作曲
somewhat|adv.稍微,有点,有些
desultory|adj.散漫的,不连贯的,断断续续的
precipitant|adj.仓促的
repossess|vt.收回,复得
neutrality|n.中立,中性
inconsequential|adj.不合逻辑的,不合理的
fungous|adj.真菌状的,有真菌特征的
athlete|n.运动员,运动选手
incipient|adj.初始的
fatalistic|adj.宿命论的
genetically|创始
minority|n.少数,少数民族
overflow|n.溢出,超值,泛滥,充满,洋溢v.(使)泛滥,(使)溢出,(使)充溢
coruscate|vi.闪烁,焕发
conventionalized|使成惯例
carbon|n.[化]碳(元素符号C),(一张)复写纸
internal|adj.内在的,国内的
introduction|n.介绍,传入,初步,导言,绪论,入门
archives|n.档案,公文,档案室,案卷保管处
sacred|adj.神的,宗教的,庄严的,神圣的
maxim|n.格言,座右铭
usual|adj.平常的,通常的,惯例的
expletive|n.感叹词,咒骂语
tub|n.浴盆
sect|n.宗派,教派,教士会,流派,部分,段
substandard|adj.标准以下的,不合规格的
barren|adj.不生育的,不孕的,贫瘠的,没有结果的,无益的,单调的,无聊的,空洞的n.荒地
forwards|adv.(forward)向前方,继续向前
poe|坡
totalitarian|adj.极权主义的n.极权主义者
pass|n.经过,关口,途径,护照,通行证,入场券,传球,及格vt.通过,审查通过,忽略,传递vi.经过,变化,流通,宣判,被忽略,终止,传递,不叫牌
feedback|n.[无]回授,反馈,反应
repellent|adj.排斥的
sparse|adj.稀少的,稀疏的
hackney|n.乘用马,出租马车,操贱役的人
scutter|n.疾走v.疾走
treatment|n.待遇,对待,处理,治疗
mariner|n.水手
converse|n.相反的事物,倒,逆行adj.相反的,颠倒的vi.谈话,交谈,认识
ankle|n.[解]踝
constancy|n.不屈不挠,坚定不移,恒久不变的状态或性质
preschool|adj.未满学龄的,入学前的n.幼儿园
complicated|adj.复杂的,难解的
national|adj.国家的,国立[有]的,民族的
dietary|adj.饭食的n.规定的食物,饮食之规定
deceptively|adv.迷惑地,虚伪地
linearity|n.线性,直线性
jurisprudence|n.法学
conqueror|n.征服者,胜利者
conjugal|adj.结婚的,夫妇间的
cursory|adj.匆匆忙忙的,粗略的,草率的`
word=word.raw_word.split('\n')
var num=randomNum(0, word.length)
                        var number = hmUI.createWidget(hmUI.widget.TEXT, {
                            x: 20,
                            y: 100 / 2,
                            w: 160,
                            h: 100,
                            color: 0x617581,
                            text_size: 20,
                            align_h: hmUI.align.CENTER_H,
                            align_v: hmUI.align.CENTER_V,
                            text_style: hmUI.text_style.NONE,
                            text: ''+sn
                        })
                        var text1 = hmUI.createWidget(hmUI.widget.TEXT, {
                            x: 20,
                            y: 300 / 2,
                            w: 160,
                            h: 100,
                            color: 0xeab007,
                            text_size: 50,
                            align_h: hmUI.align.CENTER_H,
                            align_v: hmUI.align.CENTER_V,
                            text_style: hmUI.text_style.NONE,
                            text: ''+word[num].split('|')[0]
                        })
                        text1.addEventListener(hmUI.event.CLICK_DOWN, ()=>{
                            sn += 1;
                            num=randomNum(0, word.length)
                                text1.setProperty(hmUI.prop.TEXT, word[num].split('|')[0]);
                                text2.setProperty(hmUI.prop.TEXT, splitStringByCount(''+word[num].split('|')[1], 5).join('\n'));
                                number.setProperty(hmUI.prop.TEXT, ''+sn)
                        
                        })
                        var text2 = hmUI.createWidget(hmUI.widget.TEXT, {
                            x: 20,
                            y: 300,
                            w: 160,
                            h: 100,
                            color: 0xffffff,
                            text_size: 30,
                            align_h: hmUI.align.CENTER_H,
                            align_v: hmUI.align.CENTER_V,
                            text_style: hmUI.text_style.NONE,
                            text: splitStringByCount(''+word[num].split('|')[1], 5).join('\n')
                        })
                        text2.addEventListener(hmUI.event.CLICK_DOWN, ()=>{
                            sn += 1;
                            num=randomNum(0, word.length)
                                text1.setProperty(hmUI.prop.TEXT, word[num].split('|')[0]);
                                text2.setProperty(hmUI.prop.TEXT, splitStringByCount(''+word[num].split('|')[1], 5).join('\n'));
                                number.setProperty(hmUI.prop.TEXT, ''+sn)
                        
                        })
                    },
                    onInit() {
                        console.log("index page.js on init invoke"), this.init_view();
                    },
                    onReady() {
                        console.log("index page.js on ready invoke");
                    },
                    onShow() {
                        console.log("index page.js on show invoke");
                    },
                    onHide() {
                        console.log("index page.js on hide invoke");
                    },
                    onDestory() {
                        console.log("index page.js on destory invoke");
                    }
                });
            })();
        } catch (e) {
            console.log(e);
        }
    })();
} catch (e) {
    console.log(e);
}